import AVFoundation
import CryptoKit
import DJCDomain
import Foundation

extension RekordboxWriter {
    /// 스냅샷만 읽어 초안을 만든다. 같은 음원인지 여부는 사용자가 미리 듣고 확인한다.
    public static func prepareMerge(keeping: String, removing: [String], snapshot: URL) throws -> DuplicateMergeDraft {
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        defer { db.close() }
        let target = try mergeMember(keeping, db: db)
        let sources = try removing.sorted().map { try mergeMember($0, db: db) }
        try checkMergeReferences(sources, db: db)
        _ = try DuplicateMerge.cues(keeping: target, removing: sources)
        _ = try DuplicateMerge.playlists(keeping: keeping, removing: Set(removing), in: PlaylistTree.read(db).layout)
        return DuplicateMergeDraft(keeping: target, removing: sources, base: try mergeFingerprint([keeping] + removing, db: db))
    }

    static func mergeMember(_ id: String, db: CipherDatabase) throws -> DuplicateMergeDraft.Member {
        var rows: [(uuid: String, title: String, path: String, type: Int)] = []
        try db.query("SELECT UUID, Title, FolderPath, FileType FROM djmdContent WHERE ID = ? AND rb_local_deleted = 0", [.text(id)]) {
            rows.append(($0.string(0) ?? "", $0.string(1) ?? "", $0.string(2) ?? "", $0.int(3) ?? 0))
        }
        guard rows.count == 1, let row = rows.first, row.path.hasPrefix("/"), [1, 4, 5, 11].contains(row.type),
              let info = RekordboxTimeline.packetInfo(url: URL(filePath: row.path)), info.sampleRate > 0,
              ["lpcm", "flac", "aac ", ".mp3"].contains(info.formatID),
              let audio = try? AVAudioFile(forReading: URL(filePath: row.path)) else {
            throw DuplicateMerge.Blocked(String(ui: "로컬 음원의 시간축을 읽지 못했습니다. 파일 위치와 형식을 확인하세요"))
        }
        if row.type == 1, let frames = SeekInfo.mp3Frames(url: URL(filePath: row.path)), frames.isVariableBitRate,
           !RekordboxTimeline.mp3Header(url: URL(filePath: row.path)).contains("LAME") {
            throw DuplicateMerge.Blocked(String(ui: "이 MP3 인코더의 시간축을 확인하지 못했습니다. rekordbox에서 큐를 직접 정리하세요"))
        }
        var cues: [EditableCue] = []
        try db.query("SELECT ID, Kind, InMsec, OutMsec, Comment, ActiveLoop, BeatLoopSize, rb_local_deleted FROM djmdCue WHERE ContentID = ? ORDER BY ID", [.text(id)]) {
            let cue = Cue(id: $0.string(0) ?? "", contentID: id, kind: $0.int(1) ?? -1, inMsec: $0.int(2) ?? 0,
                          name: $0.string(4) ?? "", colorTableIndex: nil, outMsec: $0.int(3) ?? 0,
                          activeLoop: $0.int(5) ?? 0, beatLoopSize: $0.int(6) ?? 0)
            guard ($0.int(7) ?? 0) == 0, let editable = EditableCue(cue) else {
                throw DuplicateMerge.Blocked(String(ui: "옮길 수 없는 큐가 있습니다. rekordbox에서 큐를 정리한 뒤 다시 합치세요"))
            }
            if !cue.isAutoGenerated { cues.append(editable) }
        }
        return .init(contentID: id, trackUUID: row.uuid, title: row.title,
                     duration: Double(audio.length) / audio.processingFormat.sampleRate,
                     offset: RekordboxTimeline.predictedOffset(url: URL(filePath: row.path)), cues: cues)
    }

    /// 지울 원본을 막을 조건. 합치기가 지울 곡 행·딸린 행(재생 목록 항목 포함)·함께 지울 앨범·아티스트 행 중 동기화 상태(≠ 0)인 것이 있으면
    /// 빼는 규칙을 확인하지 않아 막는다(#196). 원본의 재생 목록 항목은 목록 편집(`removeTracks`)이 `deleteRow`보다 먼저 지우므로 쓰기 전에
    /// 여기서 봐야 한다. 이력은 지운 뒤 뒤 순번을 당길 자리에 지운 표시 행이 있는지도 본다(재생 목록은 목록 편집이 살아 있는 행만 다시 매긴다).
    /// 확인하지 않은 표(추천 좋아요 포함)에 걸린 원본도 막는다. 남는 곡은 큐·재생 목록 편집이라 동기화 상태를 256 → 257로 올리는 검증된
    /// 쓰기 경로를 쓰므로 막지 않는다. 이유에는 지울 원본의 이름을 적는다(보고 제목은 남길 곡이다).
    static func checkMergeReferences(_ sources: [DuplicateMergeDraft.Member], db: CipherDatabase) throws {
        let all = Set(sources.map(\.contentID))
        for source in sources {
            let orphans = try RekordboxTrackWriter.orphanedRows(db, contentID: source.contentID, gone: all)
            if let reason = try RekordboxTrackWriter.removalBlock(of: source.contentID, orphans: orphans,
                                                                  renumbering: [RekordboxTrackWriter.historyTable], db: db) {
                throw DuplicateMerge.Blocked(mergeSourceReason(reason, source: source))
            }
        }
    }

    /// 합치기가 막힌 이유 앞에 지울 원본의 이름을 붙인다. 보고의 제목은 남길 곡이라 이름이 없으면 남길 곡을 빼야 하는 것처럼 읽힌다.
    public static func mergeSourceReason(_ reason: String, title: String) -> String {
        String(ui: "뺄 곡 ‘\(title)’: \(reason)")
    }

    static func mergeSourceReason(_ reason: String, source: DuplicateMergeDraft.Member) -> String {
        mergeSourceReason(reason, title: source.title.isEmpty ? source.contentID : source.title)
    }

    /// 삭제로 잃을 정보·목록 전체·음원 내용까지 비교한다. 인증 표는 읽지 않는다.
    static func mergeFingerprint(_ ids: [String], db: CipherDatabase) throws -> String {
        let values = ids.sorted().map(CipherDatabase.Value.text)
        let placeholders = Array(repeating: "?", count: values.count).joined(separator: ",")
        var records: [[String?]] = []
        for table in ["djmdContent", "djmdCue", "contentCue", "contentFile", "djmdMixerParam", "djmdSongHistory"] {
            let column = table == "djmdContent" ? "ID" : "ContentID"
            try db.query("SELECT * FROM \(table) WHERE \(column) IN (\(placeholders)) ORDER BY ID", values) { row in
                records.append([table] + (0..<row.count).map { row.string(Int32($0)) })
            }
        }
        let lists = "SELECT PlaylistID FROM djmdSongPlaylist WHERE ContentID IN (\(placeholders))"
        for (table, column) in [("djmdPlaylist", "ID"), ("djmdSongPlaylist", "PlaylistID")] {
            try db.query("SELECT * FROM \(table) WHERE \(column) IN (\(lists)) ORDER BY ID", values) { row in
                records.append([table] + (0..<row.count).map { row.string(Int32($0)) })
            }
        }
        try db.query("SELECT FolderPath FROM djmdContent WHERE ID IN (\(placeholders)) ORDER BY ID", values) { row in
            let handle = try FileHandle(forReadingFrom: URL(filePath: row.string(0) ?? ""))
            defer { try? handle.close() }
            var digest = SHA256()
            while let data = try handle.read(upToCount: 1 << 20), !data.isEmpty { digest.update(data: data) }
            records.append([digest.finalize().map { String(format: "%02x", $0) }.joined()])
        }
        return SHA256.hash(data: try JSONEncoder().encode(records)).map { String(format: "%02x", $0) }.joined()
    }

    static func checkMerge(_ draft: DuplicateMergeDraft, db: CipherDatabase) throws -> CueDraft {
        try checkMergeReferences(draft.removing, db: db)
        guard !draft.removing.isEmpty, try mergeFingerprint(draft.members.map(\.contentID), db: db) == draft.base else {
            throw DuplicateMerge.Blocked(String(ui: "합치기 초안 뒤 곡·큐·재생 목록·음원이 바뀌었습니다. 초안을 버리고 다시 만드세요"))
        }
        let target = try mergeMember(draft.keeping.contentID, db: db)
        let sources = try draft.removing.map { try mergeMember($0.contentID, db: db) }
        guard target.trackUUID == draft.keeping.trackUUID, zip(sources, draft.removing).allSatisfy({ $0.trackUUID == $1.trackUUID }) else {
            throw DuplicateMerge.Blocked(String(ui: "서로 다른 곡을 골라 합치기 초안을 다시 만드세요"))
        }
        return try DuplicateMerge.cues(keeping: target, removing: sources)
    }

    struct MergeExpectation {
        var draft: DuplicateMergeDraft
        var cue: Expectation?
        var fileWarning: String?
    }

    /// - Parameter renumbered: 원본을 빼며 뒤 순번을 당긴 행의 기대 값. 한 번에 쓰는 묶음들이 같은 이력을 차례로 당기므로 묶음마다 따로 두지 않고
    ///   이어 간다(`RekordboxTrackWriter.Renumbered`). 막혀 되돌리는 묶음의 몫은 부른 쪽이 SAVEPOINT와 함께 되돌린다.
    static func applyMerge(_ draft: DuplicateMergeDraft, cue: CueDraft, work: inout PlaylistWork,
                           db: CipherDatabase, usn: inout Int, stamp: (db: String, json: String), share: URL?,
                           renumbered: inout RekordboxTrackWriter.Renumbered) throws
        -> (expectation: MergeExpectation, files: [URL]) {
        var expectation = MergeExpectation(draft: draft)
        if cue.hasChanges { expectation.cue = try apply(cue, db: db, usn: &usn, stamp: stamp).expectation }
        for edit in try DuplicateMerge.playlists(keeping: draft.keeping.contentID, removing: Set(draft.removing.map(\.contentID)), in: work.tree.layout) {
            _ = try applyPlaylist(edit, work: &work, db: db, usn: &usn, stamp: stamp)
        }
        var files: [URL] = []
        for source in draft.removing {
            let plan = try deletionFiles(source.contentID, db: db, share: share)
            do {
                _ = try RekordboxTrackWriter.deleteRow(source.contentID, db: db, usn: &usn, stamp: stamp, renumbered: &renumbered)
            } catch let blocked as RekordboxTrackWriter.Blocked {
                // 사전 검사가 먼저 보지만, 여기서 막혀도 어느 원본인지 알린다
                throw DuplicateMerge.Blocked(mergeSourceReason(blocked.reason, source: source))
            }
            files += plan.files
            if let warning = plan.warning { expectation.fileWarning = warning }
        }
        try verifyMerge(expectation, db: db)
        try RekordboxTrackWriter.verifyRenumbered(renumbered, db: db)
        return (expectation, files)
    }

    static func verifyMerge(_ expectation: MergeExpectation, db: CipherDatabase) throws {
        if let cue = expectation.cue { try verify(db: db, contentID: expectation.draft.keeping.contentID, cue) }
        for member in expectation.draft.removing {
            for (table, column) in [("djmdContent", "ID"), ("djmdCue", "ContentID"), ("contentCue", "ContentID"),
                                    ("contentFile", "ContentID"), ("djmdMixerParam", "ContentID"), ("djmdSongPlaylist", "ContentID"), ("djmdSongHistory", "ContentID")] {
                guard try scalar(db, "SELECT count(*) FROM \(table) WHERE \(column) = ?", [.text(member.contentID)]) == 0 else {
                    throw DJCError.writeVerificationFailed(String(ui: "지운 곡의 참조가 남아 있습니다"))
                }
            }
        }
    }

    public static func mergeDrafts(in backup: URL) -> [DuplicateMergeDraft] {
        guard let data = try? Data(contentsOf: backup.appending(path: "merge-drafts.json")) else { return [] }
        return (try? JSONDecoder().decode([DuplicateMergeDraft].self, from: data)) ?? []
    }
}
