import AVFoundation
import CryptoKit
import DJCDomain
import Foundation

extension RekordboxWriter {
    /// 스냅샷만 읽어 초안을 만든다. 같은 음원인지 여부는 사용자가 미리 듣고 확인한다.
    public static func prepareMerge(keeping: String, removing: [String], snapshot: URL) throws -> DuplicateMergeDraft {
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        defer { db.close() }
        let target = try mergeMember(keeping, db: db)
        let sources = try removing.sorted().map { try mergeMember($0, db: db) }
        for source in sources { try checkMergeReferences(source.contentID, db: db) }
        _ = try DuplicateMerge.cues(keeping: target, removing: sources)
        _ = try DuplicateMerge.playlists(keeping: keeping, removing: Set(removing), in: PlaylistTree.read(db).layout)
        return DuplicateMergeDraft(keeping: target, removing: sources, base: try mergeFingerprint([keeping] + removing, db: db))
    }

    static func mergeMember(_ id: String, db: CipherDatabase) throws -> DuplicateMergeDraft.Member {
        var rows: [(uuid: String, title: String, path: String, type: Int)] = []
        try db.query("SELECT UUID, Title, FolderPath, FileType FROM djmdContent WHERE ID = ? AND rb_local_deleted = 0", [.text(id)]) {
            rows.append(($0.string(0) ?? "", $0.string(1) ?? "", $0.string(2) ?? "", $0.int(3) ?? 0))
        }
        guard rows.count == 1, let row = rows.first, row.path.hasPrefix("/"), [1, 4, 5, 11].contains(row.type),
              let info = RekordboxTimeline.packetInfo(url: URL(filePath: row.path)), info.sampleRate > 0,
              ["lpcm", "flac", "aac ", ".mp3"].contains(info.formatID),
              let audio = try? AVAudioFile(forReading: URL(filePath: row.path)) else {
            throw DuplicateMerge.Blocked(String(ui: "로컬 음원의 시간축을 읽지 못했습니다. 파일 위치와 형식을 확인하세요"))
        }
        if row.type == 1, let frames = SeekInfo.mp3Frames(url: URL(filePath: row.path)), frames.isVariableBitRate,
           !RekordboxTimeline.mp3Header(url: URL(filePath: row.path)).contains("LAME") {
            throw DuplicateMerge.Blocked(String(ui: "이 MP3 인코더의 시간축을 확인하지 못했습니다. rekordbox에서 큐를 직접 정리하세요"))
        }
        var cues: [EditableCue] = []
        try db.query("SELECT ID, Kind, InMsec, OutMsec, Comment, ActiveLoop, BeatLoopSize, rb_local_deleted FROM djmdCue WHERE ContentID = ? ORDER BY ID", [.text(id)]) {
            let cue = Cue(id: $0.string(0) ?? "", contentID: id, kind: $0.int(1) ?? -1, inMsec: $0.int(2) ?? 0,
                          name: $0.string(4) ?? "", colorTableIndex: nil, outMsec: $0.int(3) ?? 0,
                          activeLoop: $0.int(5) ?? 0, beatLoopSize: $0.int(6) ?? 0)
            guard ($0.int(7) ?? 0) == 0, let editable = EditableCue(cue) else {
                throw DuplicateMerge.Blocked(String(ui: "옮길 수 없는 큐가 있습니다. rekordbox에서 큐를 정리한 뒤 다시 합치세요"))
            }
            if !cue.isAutoGenerated { cues.append(editable) }
        }
        return .init(contentID: id, trackUUID: row.uuid, title: row.title,
                     duration: Double(audio.length) / audio.processingFormat.sampleRate,
                     offset: RekordboxTimeline.predictedOffset(url: URL(filePath: row.path)), cues: cues)
    }

    static func checkMergeReferences(_ id: String, db: CipherDatabase) throws {
        for table in RekordboxTrackWriter.unverifiedReferenceTables {
            if try scalar(db, "SELECT count(*) FROM \(table) WHERE ContentID = ?", [.text(id)]) ?? 0 > 0 {
                throw DuplicateMerge.Blocked(String(ui: "\(table)에도 들어 있는 곡이라 아직 지우지 않습니다(rekordbox에서 지우세요)"))
            }
        }
    }

    /// 삭제로 잃을 정보·목록 전체·음원 내용까지 비교한다. 인증 표는 읽지 않는다.
    static func mergeFingerprint(_ ids: [String], db: CipherDatabase) throws -> String {
        let values = ids.sorted().map(CipherDatabase.Value.text)
        let placeholders = Array(repeating: "?", count: values.count).joined(separator: ",")
        var records: [[String?]] = []
        for table in ["djmdContent", "djmdCue", "contentCue", "contentFile", "djmdMixerParam", "djmdSongHistory"] {
            let column = table == "djmdContent" ? "ID" : "ContentID"
            try db.query("SELECT * FROM \(table) WHERE \(column) IN (\(placeholders)) ORDER BY ID", values) { row in
                records.append([table] + (0..<row.count).map { row.string(Int32($0)) })
            }
        }
        let lists = "SELECT PlaylistID FROM djmdSongPlaylist WHERE ContentID IN (\(placeholders))"
        for (table, column) in [("djmdPlaylist", "ID"), ("djmdSongPlaylist", "PlaylistID")] {
            try db.query("SELECT * FROM \(table) WHERE \(column) IN (\(lists)) ORDER BY ID", values) { row in
                records.append([table] + (0..<row.count).map { row.string(Int32($0)) })
            }
        }
        try db.query("SELECT FolderPath FROM djmdContent WHERE ID IN (\(placeholders)) ORDER BY ID", values) { row in
            let handle = try FileHandle(forReadingFrom: URL(filePath: row.string(0) ?? ""))
            defer { try? handle.close() }
            var digest = SHA256()
            while let data = try handle.read(upToCount: 1 << 20), !data.isEmpty { digest.update(data: data) }
            records.append([digest.finalize().map { String(format: "%02x", $0) }.joined()])
        }
        return SHA256.hash(data: try JSONEncoder().encode(records)).map { String(format: "%02x", $0) }.joined()
    }

    static func checkMerge(_ draft: DuplicateMergeDraft, db: CipherDatabase) throws -> CueDraft {
        for source in draft.removing { try checkMergeReferences(source.contentID, db: db) }
        guard !draft.removing.isEmpty, try mergeFingerprint(draft.members.map(\.contentID), db: db) == draft.base else {
            throw DuplicateMerge.Blocked(String(ui: "합치기 초안 뒤 곡·큐·재생 목록·음원이 바뀌었습니다. 초안을 버리고 다시 만드세요"))
        }
        let target = try mergeMember(draft.keeping.contentID, db: db)
        let sources = try draft.removing.map { try mergeMember($0.contentID, db: db) }
        guard target.trackUUID == draft.keeping.trackUUID, zip(sources, draft.removing).allSatisfy({ $0.trackUUID == $1.trackUUID }) else {
            throw DuplicateMerge.Blocked(String(ui: "서로 다른 곡을 골라 합치기 초안을 다시 만드세요"))
        }
        return try DuplicateMerge.cues(keeping: target, removing: sources)
    }

    struct MergeExpectation {
        var draft: DuplicateMergeDraft
        var cue: Expectation?
    }

    static func applyMerge(_ draft: DuplicateMergeDraft, cue: CueDraft, work: inout PlaylistWork,
                           db: CipherDatabase, usn: inout Int, stamp: (db: String, json: String), share: URL?) throws
        -> (expectation: MergeExpectation, directories: [URL]) {
        var expectation = MergeExpectation(draft: draft)
        if cue.hasChanges { expectation.cue = try apply(cue, db: db, usn: &usn, stamp: stamp).expectation }
        for edit in try DuplicateMerge.playlists(keeping: draft.keeping.contentID, removing: Set(draft.removing.map(\.contentID)), in: work.tree.layout) {
            _ = try applyPlaylist(edit, work: &work, db: db, usn: &usn, stamp: stamp)
        }
        var directories: [URL] = []
        var audioDirectories = Set<String>()
        for source in draft.removing {
            try db.query("SELECT FolderPath FROM djmdContent WHERE ID = ?", [.text(source.contentID)]) {
                if let path = $0.string(0) {
                    audioDirectories.insert(URL(filePath: path).resolvingSymlinksInPath().deletingLastPathComponent().path)
                }
            }
            directories += try RekordboxTrackWriter.deleteRow(source.contentID, db: db, usn: &usn, stamp: stamp, share: share).directories
        }
        guard directories.allSatisfy({ !audioDirectories.contains($0.resolvingSymlinksInPath().path) }) else {
            throw DuplicateMerge.Blocked(String(ui: "분석 파일 경로가 안전하지 않습니다. rekordbox에서 분석 파일을 다시 만든 뒤 합치세요"))
        }
        try verifyMerge(expectation, db: db)
        return (expectation, directories)
    }

    static func verifyMerge(_ expectation: MergeExpectation, db: CipherDatabase) throws {
        if let cue = expectation.cue { try verify(db: db, contentID: expectation.draft.keeping.contentID, cue) }
        for member in expectation.draft.removing {
            for (table, column) in [("djmdContent", "ID"), ("djmdCue", "ContentID"), ("contentCue", "ContentID"),
                                    ("contentFile", "ContentID"), ("djmdMixerParam", "ContentID"), ("djmdSongPlaylist", "ContentID"), ("djmdSongHistory", "ContentID")] {
                guard try scalar(db, "SELECT count(*) FROM \(table) WHERE \(column) = ?", [.text(member.contentID)]) == 0 else {
                    throw DJCError.writeVerificationFailed(String(ui: "지운 곡의 참조가 남아 있습니다"))
                }
            }
        }
    }

    /// 삭제할 분석·그림은 커밋 전에 백업한다. 다른 곡과 폴더를 공유하면 삭제하지 않는다.
    static func backupMergeFiles(_ directories: [URL], db: CipherDatabase, share: URL?, backup: URL?) throws -> [URL] {
        guard !directories.isEmpty, let share else { return [] }
        let root = share.resolvingSymlinksInPath().standardizedFileURL.path + "/"
        var referenced = Set<String>()
        try db.query("SELECT AnalysisDataPath, ImagePath, FolderPath FROM djmdContent") { row in
            for column: Int32 in [0, 1] {
                if let url = RekordboxShare.analysisURL(row.string(column), root: share) {
                    referenced.insert(url.deletingLastPathComponent().resolvingSymlinksInPath().path)
                }
            }
            if let path = row.string(2), path.hasPrefix("/") {
                referenced.insert(URL(filePath: path).resolvingSymlinksInPath().deletingLastPathComponent().path)
            }
        }
        var files: [URL] = []
        for directory in Set(directories) {
            let resolved = directory.resolvingSymlinksInPath().standardizedFileURL
            guard ["PIONEER/USBANLZ/", "PIONEER/Artwork/"].contains(where: { resolved.path.hasPrefix(root + $0) }) else {
                throw DuplicateMerge.Blocked(String(ui: "분석 파일 경로가 안전하지 않습니다. rekordbox에서 분석 파일을 다시 만든 뒤 합치세요"))
            }
            guard resolved.path.hasPrefix(root), resolved.path == directory.standardizedFileURL.path,
                  !referenced.contains(resolved.path) else {
                throw DuplicateMerge.Blocked(String(ui: "분석 파일 폴더가 연결되었거나 다른 곡과 공유됩니다. rekordbox에서 직접 정리하세요"))
            }
            if FileManager.default.fileExists(atPath: directory.path) {
                for file in try FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: [.isRegularFileKey, .isSymbolicLinkKey]) {
                    let info = try file.resourceValues(forKeys: [.isRegularFileKey, .isSymbolicLinkKey])
                    guard info.isRegularFile == true, info.isSymbolicLink != true else {
                        throw DuplicateMerge.Blocked(String(ui: "분석 파일 폴더가 연결되었거나 다른 곡과 공유됩니다. rekordbox에서 직접 정리하세요"))
                    }
                    files.append(file)
                }
            }
        }
        if let backup {
            let folder = backup.appending(path: "anlz")
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
            let manifestURL = folder.appending(path: "manifest.json")
            var manifest = (try? Data(contentsOf: manifestURL)).flatMap { try? JSONDecoder().decode([String: String].self, from: $0) } ?? [:]
            for file in files {
                let name = "merge-\(manifest.count).\(file.pathExtension)"
                try FileManager.default.copyItem(at: file, to: folder.appending(path: name))
                manifest[name] = file.path
            }
            try JSONEncoder().encode(manifest).write(to: manifestURL, options: .atomic)
        }
        return files
    }

    public static func mergeDrafts(in backup: URL) -> [DuplicateMergeDraft] {
        guard let data = try? Data(contentsOf: backup.appending(path: "merge-drafts.json")) else { return [] }
        return (try? JSONDecoder().decode([DuplicateMergeDraft].self, from: data)) ?? []
    }
}
