import Foundation

/// anicue 안에서 편집하는 큐. rekordbox에는 쓰지 않는다(검증된 반영 경로를 통해서만 나간다).
public struct EditableCue: Codable, Identifiable, Hashable, Sendable {
    public enum Kind: Codable, Hashable, Sendable {
        case memory
        /// 0…7 = A…H
        case hot(Int)

        public var slotLetter: String? {
            if case let .hot(slot) = self { return String(UnicodeScalar(UInt8(65 + slot))) }
            return nil
        }
    }

    public var id: UUID
    /// rekordbox `djmdCue.ID`. rekordbox에서 불러온 큐만 가진다.
    public var sourceID: String?
    public var kind: Kind
    public var time: Double
    public var name: String

    public init(id: UUID = UUID(), sourceID: String? = nil, kind: Kind, time: Double, name: String = "") {
        self.id = id
        self.sourceID = sourceID
        self.kind = kind
        self.time = time
        self.name = name
    }

    /// rekordbox 큐 → 편집용. Kind 매핑은 실측 분포 기반(1,2,3 → A,B,C / 5…9 → D…H).
    /// 자동 생성 이름과 의미 미확인 Kind(4)는 편집 대상에서 뺀다.
    public init?(_ cue: Cue) {
        let kind: Kind
        switch cue.kind {
        case 0: kind = .memory
        case 1, 2, 3: kind = .hot(cue.kind - 1)
        case 5...9: kind = .hot(cue.kind - 2)
        default: return nil
        }
        self.init(sourceID: cue.id, kind: kind, time: Double(cue.inMsec) / 1000,
                  name: cue.isAutoGenerated ? "" : cue.name)
    }
}

/// 곡 하나의 큐 초안. `base`는 편집을 시작할 때의 rekordbox 상태다.
public struct CueDraft: Codable, Sendable {
    public var trackUUID: String
    public var base: [EditableCue]
    public var cues: [EditableCue]

    public init(trackUUID: String, rekordboxCues: [Cue]) {
        self.trackUUID = trackUUID
        base = rekordboxCues.filter { !$0.isAutoGenerated }.compactMap(EditableCue.init).sorted { $0.time < $1.time }
        cues = base
    }

    public enum Change: Hashable, Sendable {
        case added(EditableCue)
        case removed(EditableCue)
        case modified(from: EditableCue, to: EditableCue)
    }

    /// rekordbox 상태(`base`) 대비 변경. 시각은 1ms 미만 차이를 무시한다.
    public var changes: [Change] {
        let current = Dictionary(uniqueKeysWithValues: cues.map { ($0.id, $0) })
        var result: [Change] = []
        for old in base {
            guard let new = current[old.id] else { result.append(.removed(old)); continue }
            if old.kind != new.kind || abs(old.time - new.time) >= 0.001 || old.name != new.name {
                result.append(.modified(from: old, to: new))
            }
        }
        let baseIDs = Set(base.map(\.id))
        result += cues.filter { !baseIDs.contains($0.id) }.map(Change.added)
        return result
    }

    public var hasChanges: Bool { !changes.isEmpty }

    /// 같은 슬롯의 핫큐는 하나만. 새로 놓는 쪽이 이긴다(기존 것은 제거).
    public mutating func place(_ cue: EditableCue) {
        if case .hot = cue.kind { cues.removeAll { $0.kind == cue.kind && $0.id != cue.id } }
        if let index = cues.firstIndex(where: { $0.id == cue.id }) {
            cues[index] = cue
        } else {
            cues.append(cue)
        }
        cues.sort { $0.time < $1.time }
    }

    public mutating func remove(_ id: EditableCue.ID) {
        cues.removeAll { $0.id == id }
    }

    public mutating func revert() {
        cues = base
    }

    /// rekordbox로 내보내기 전 확인할 문제. 반영 경로 검증(V1) 때 기준을 확정한다.
    public func issues(duration: Double) -> [String] {
        var issues: [String] = []
        let slots = cues.compactMap(\.kind.slotLetter)
        if Set(slots).count != slots.count { issues.append("같은 핫큐 슬롯이 두 번 쓰였습니다") }
        if cues.contains(where: { $0.time < 0 || $0.time > duration }) { issues.append("곡 길이를 벗어난 큐가 있습니다") }
        return issues
    }
}

/// 초안은 곡 UUID별 JSON으로 Application Support에 둔다.
public enum CueDraftStore {
    /// rekordbox에 반영이 확인된 곡의 초안을 지운다(이제 rekordbox 값이 원본이다).
    public static func remove(trackUUID: String) {
        try? FileManager.default.removeItem(at: directory.appending(path: "\(trackUUID).json"))
    }

    public static var directory: URL {
        AnicuePaths.userData.appending(path: "cue-drafts")
    }

    public static func load(trackUUID: String) -> CueDraft? {
        let url = directory.appending(path: "\(trackUUID).json")
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(CueDraft.self, from: data)
    }

    public static func save(_ draft: CueDraft) throws {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appending(path: "\(draft.trackUUID).json")
        if draft.hasChanges {
            try JSONEncoder().encode(draft).write(to: url, options: .atomic)
        } else {
            try? FileManager.default.removeItem(at: url)
        }
    }
}

// MARK: - 시간축 이동

public extension CueDraft {
    /// 모든 큐(원본 포함)를 옮긴다. rekordbox 시간축 ↔ anicue 시간축 변환에 쓴다.
    func shifted(by seconds: Double) -> CueDraft {
        guard seconds != 0 else { return self }
        var copy = self
        copy.base = base.map { var cue = $0; cue.time += seconds; return cue }
        copy.cues = cues.map { var cue = $0; cue.time += seconds; return cue }
        return copy
    }
}
