import Foundation

public struct Track: Sendable, Identifiable, Hashable {
    public let id: String
    public let uuid: String
    public let title: String
    public let artist: String?
    public let album: String?
    public let albumArtist: String?
    public let genre: String?
    public let composer: String?
    public let releaseYear: Int?
    public let trackNumber: Int?
    public let key: String?
    /// rekordbox는 BPM을 100배 정수로 저장한다. 미분석이면 nil.
    public let bpm: Double?
    public let lengthSeconds: Int
    public let folderPath: String
    /// DB에 저장된 코멘트 원문(정규화 전).
    public let comment: String
    /// `created_at` 앞 10자리(YYYY-MM-DD). 컬렉션 임포트 시점으로 쓴다.
    public let importedOn: String?
    public let analysisDataPath: String?
    /// `/PIONEER/Artwork/…/artwork.jpg` (rekordbox share 기준)
    public let imagePath: String?
    /// 컬렉션에서 삭제됐지만 행이 남아 있는 tombstone.
    public let isDeleted: Bool

    /// 스트리밍 트랙(`apple-music:…`, `spotify:…` 등)은 로컬 파일 경로가 없다.
    public var isStreaming: Bool { !folderPath.hasPrefix("/") }

    public var importYear: String? { importedOn.map { String($0.prefix(4)) } }

    public var fileExtension: String {
        isStreaming ? "stream" : (folderPath as NSString).pathExtension.lowercased()
    }
}

public struct Cue: Sendable, Hashable {
    /// `djmdCue.ID`
    public let id: String
    public let contentID: String
    /// 0 = 메모리 큐, 그 외 = 핫큐 슬롯. `hotCueSlot` 참고.
    public let kind: Int
    public let inMsec: Int
    public let name: String
    public let colorTableIndex: Int?

    public var isMemoryCue: Bool { kind == 0 }

    /// rekordbox가 자동으로 붙이는 이름. 이 이름의 큐는 사용자가 직접 찍은 큐로 보지 않는다.
    public static let autoNames: Set<String> = ["CUE(Auto)", "1.1Bars"]
    public var isAutoGenerated: Bool { Cue.autoNames.contains(name.trimmingCharacters(in: .whitespaces)) }

    /// 실측 분포 기반 매핑(1,2,3 → A,B,C / 5…9 → D…H). Kind 4의 의미는 미확인.
    public var hotCueSlot: Character? {
        switch kind {
        case 1: "A"
        case 2: "B"
        case 3: "C"
        case 5: "D"
        case 6: "E"
        case 7: "F"
        case 8: "G"
        case 9: "H"
        default: nil
        }
    }
}
