import AnicueCore
import Foundation

/// 표 한 줄. 로드할 때 한 번 분류·파싱해 두고 화면에서는 읽기만 한다.
struct TrackRow: Identifiable, Hashable, Sendable {
    enum CueState: String, Sendable {
        case manual = "수동"
        case autoOnly = "자동만"
        case none = "없음"
    }

    let track: Track
    let cues: [Cue]
    let commentClass: CommentClass
    let parsed: ConventionComment?
    let playCount: Int
    let cueState: CueState
    let manualCueCount: Int

    var id: String { track.id }
    /// rekordbox는 Spotify 곡의 제목·아티스트를 `$A7:v1:…`로 암호화해 저장한다.
    var isEncrypted: Bool { track.title.hasPrefix("$A7:") }
    var title: String { isEncrypted ? "🔒 Spotify 곡 (제목 암호화됨)" : track.title }
    var artist: String { isEncrypted ? "" : track.artist ?? "" }
    var comment: String { track.comment }
    var commentClassName: String { commentClass.displayName }
    var importedOn: String { track.importedOn ?? "" }
    var cueStateName: String { cueState.rawValue }
    var bpmValue: Double { track.bpm ?? 0 }
    var genre: String { track.genre ?? "" }
    var keyName: String { track.key ?? "" }

    /// 검색용 소문자 키(제목·아티스트·코멘트·장르). 로딩 때 한 번만 만든다.
    let searchKey: String

    init(track: Track, cues: [Cue], playCount: Int) {
        self.track = track
        self.cues = cues.sorted { $0.inMsec < $1.inMsec }
        self.playCount = playCount
        // 정규화는 한 번만 하고 분류·파싱이 같이 쓴다.
        let normalized = CommentText.normalize(track.comment)
        commentClass = CommentClassifier.classify(normalized: normalized)
        parsed = commentClass == .convention ? ConventionParser.parse(normalized: normalized) : nil
        let encrypted = track.title.hasPrefix("$A7:")
        searchKey = [encrypted ? "" : track.title, encrypted ? "" : (track.artist ?? ""), track.comment, track.genre ?? ""]
            .joined(separator: "\u{1F}").lowercased()
        let manual = cues.filter { !$0.isAutoGenerated }
        manualCueCount = manual.count
        cueState = cues.isEmpty ? .none : (manual.isEmpty ? .autoOnly : .manual)
    }
}

extension CommentClass {
    var displayName: String {
        switch self {
        case .convention: "규칙"
        case .legacy: "구형"
        case .residue: "잔재"
        case .credit: "크레딧"
        case .empty: "빈 값"
        case .other: "기타"
        }
    }
}

enum LibraryFilter: String, CaseIterable, Identifiable, Sendable {
    case backlog = "빈 코멘트 (2025~26 파일)"
    case emptyComment = "빈 코멘트 전체"
    case offConvention = "규칙 밖 코멘트"
    case noCues = "큐 없음"
    case played = "재생한 곡"
    case streaming = "스트리밍"
    case all = "전체"

    var id: String { rawValue }

    var systemImage: String {
        switch self {
        case .backlog: "tray.full"
        case .emptyComment: "text.badge.xmark"
        case .offConvention: "exclamationmark.bubble"
        case .noCues: "flag.slash"
        case .played: "play.circle"
        case .streaming: "antenna.radiowaves.left.and.right"
        case .all: "music.note.list"
        }
    }

    func includes(_ row: TrackRow) -> Bool {
        switch self {
        // 툴이 파일 태그로 코멘트를 쓸 수 있는 로컬 파일만. 스트리밍은 별도 필터.
        case .backlog: row.commentClass == .empty && !row.track.isStreaming
            && ["2025", "2026"].contains(row.track.importYear ?? "")
        case .emptyComment: row.commentClass == .empty
        case .offConvention: [.legacy, .residue, .credit, .other].contains(row.commentClass)
        case .noCues: row.cueState == .none
        case .played: row.playCount > 0
        case .streaming: row.track.isStreaming
        case .all: true
        }
    }
}

extension Double {
    /// `m:ss.ss`
    var clockText: String {
        String(format: "%d:%05.2f", Int(self) / 60, truncatingRemainder(dividingBy: 60))
    }
}
