import DJCAnalysis
import DJCDomain
import DJCStorage
import AppKit
import Foundation
import RekordboxKit

/// 큐 편집(초안만 바뀐다, 규칙은 `CueDraft` 확장)
extension DeckModel {
    // MARK: - 큐 편집 (초안만 바뀐다)

    func snapped(_ time: Double) -> Double {
        let clamped = min(max(time, 0), duration)
        return quantize ? (grid?.snap(clamped) ?? clamped) : clamped
    }

    func cue(_ id: EditableCue.ID?) -> EditableCue? { draft?.cue(id) }

    func hotCue(slot: Int) -> EditableCue? { draft?.hotCue(slot: slot) }

    /// rekordbox 자동 큐("1.1Bars" 등). 초안에는 없지만 메모리 큐 한도에 든다.
    var autoMemoryCueCount: Int { row?.cues.filter { $0.isMemoryCue && $0.isAutoGenerated }.count ?? 0 }

    /// 이 곡의 메모리 큐 수(초안 + 자동 큐)
    var memoryCueCount: Int { draft?.memoryCount(autoCues: autoMemoryCueCount) ?? autoMemoryCueCount }

    func addMemoryCue(at time: Double) {
        storeMemoryCue(at: snapped(time), loop: nil)
    }

    /// + 메모리 큐 · M: 즉석 루프 중이면 그 루프를 메모리 루프로 저장하고, 아니면 플레이헤드에 메모리 큐를 찍는다.
    func addMemoryCueAtPlayhead() {
        guard let loop = instantLoop else {
            addMemoryCue(at: currentTime)
            return
        }
        guard let id = storeMemoryCue(at: loop.start, loop: EditableCue.Loop(end: loop.end, active: false, beats: loop.beats)) else { return }
        instantLoop = nil
        engagedLoopID = id
    }

    /// 메모리 큐(루프)를 더한다. 같은 자리(±30ms)에 있으면 그 큐를 고르고, rekordbox 한도(10개)면 알린다. 새로 만들면 그 ID.
    @discardableResult
    func storeMemoryCue(at time: Double, loop: EditableCue.Loop?) -> EditableCue.ID? {
        guard var edited = draft, !isWriteLocked else { return nil }
        switch edited.addMemory(at: time, loop: loop, autoCues: autoMemoryCueCount) {
        case let .existing(id):
            selectedCueID = id
            return nil
        case .limitReached:
            showToast("메모리 큐는 곡당 \(CueDraft.memoryLimit)개까지입니다(rekordbox 제한, 자동 큐 포함)")
            return nil
        case let .added(id):
            mutate { $0 = edited }
            selectedCueID = id
            return id
        }
    }

    /// 재생 위치(±30ms, 퀀타이즈 위치 포함)에 있는 메모리 큐를 지운다. CDJ에서 메모리 큐를 불러온 자리에서 DELETE를 누르는 것과 같다.
    @discardableResult
    func deleteMemoryCue(at time: Double) -> Bool {
        guard let cue = draft?.memoryCue(near: [time, snapped(time)], closestTo: time) else { return false }
        delete(cue.id)
        return true
    }

    func pressHotCue(slot: Int) {
        if let cue = hotCue(slot: slot) {
            // 루프 핫큐: 누르면 그 루프를 반복하고, 반복 중에 다시 누르면 빠져나온다.
            if cue.loop != nil, engagedLoopID == cue.id {
                engagedLoopID = nil
                return
            }
            seek(cue.time)
            if cue.loop != nil { instantLoop = nil; engagedLoopID = cue.id; syncAudioLoop() }
            selectedCueID = cue.id
        } else if let loop = instantLoop {
            // 즉석 루프 중에 빈 칸을 누르면 그 루프를 루프 핫큐로 저장하고 계속 반복한다(CDJ와 같다).
            var cue = EditableCue(kind: .hot(slot), time: loop.start)
            cue.loop = EditableCue.Loop(end: loop.end, active: false, beats: loop.beats)
            mutate { $0.place(cue) }
            instantLoop = nil
            engagedLoopID = cue.id
            selectedCueID = cue.id
        } else {
            guard canPlay || grid != nil else { return }  // 소리·그리드 없이 0초에 박히지 않게
            let cue = EditableCue(kind: .hot(slot), time: snapped(currentTime))
            mutate { $0.place(cue) }
            selectedCueID = cue.id
        }
    }

    /// 그 칸의 핫큐를 지운다(초안만, 되돌리기 가능).
    func deleteHotCue(slot: Int) {
        guard let cue = hotCue(slot: slot) else { return }
        delete(cue.id)
    }

    func moveHotCueToPlayhead(slot: Int) {
        guard var cue = hotCue(slot: slot) else { return }
        cue.time = snapped(currentTime)
        mutate { $0.place(cue) }
    }

    /// 옮긴다(퀀타이즈면 박에 맞춤). 루프는 길이를 유지한다.
    func move(_ id: EditableCue.ID, to time: Double, save: Bool = true) {
        let target = snapped(time)
        guard let cue = cue(id), abs(target - cue.time) >= 0.0005 else { return }
        mutate(save: save) { $0.move(id, to: target) }
    }

    /// 박 단위로 민다(그리드가 없으면 0.5초).
    func nudge(_ id: EditableCue.ID, beats: Int) {
        guard let cue = cue(id) else { return }
        let target = grid?.nudge(cue.time, beats: beats) ?? min(max(cue.time + Double(beats) * 0.5, 0), duration)
        mutate { $0.move(id, to: target) }
    }

    // MARK: 루프

    /// 큐를 박 수만큼의 루프로 만든다(nil이면 루프를 없앤다). 그리드가 있으면 박에 맞춘다.
    func setLoop(_ id: EditableCue.ID, beats: Int?) {
        guard let cue = cue(id) else { return }
        guard let beats else {
            mutate { $0.setLoop(id, end: nil, beats: nil) }
            return
        }
        guard let end = loopEnd(from: cue.time, beats: Double(beats)) else { return }
        mutate { $0.setLoop(id, end: end, beats: Double(beats)) }
    }

    /// 활성 루프 켜기·끄기(곡을 불러오면 그 루프를 자동으로 반복한다). 곡에 하나만 둔다.
    func toggleActiveLoop(_ id: EditableCue.ID) {
        guard cue(id)?.loop != nil else { return }
        mutate { $0.toggleActiveLoop(id) }
    }

    /// 루프 박 수(그리드 기준, 대략)
    func loopBeats(_ cue: EditableCue) -> Int? { LoopRules.beats(of: cue, grid: grid, bpm: gridBPM) }

    func setKind(_ id: EditableCue.ID, _ kind: EditableCue.Kind) {
        guard var cue = cue(id) else { return }
        cue.kind = kind
        mutate { $0.place(cue) }
    }

    func rename(_ id: EditableCue.ID, _ name: String) {
        guard var cue = cue(id) else { return }
        cue.name = name
        mutate { $0.place(cue) }
    }

    func delete(_ id: EditableCue.ID) {
        mutate { $0.remove(id) }
        if selectedCueID == id { selectedCueID = nil }
    }

    func acceptSuggestion(_ time: Double) {
        addMemoryCue(at: time)
    }

    func revertDraft() {
        mutate { $0.revert() }
        selectedCueID = nil
    }

    func commitDraft() {
        if !isWriteLocked, let draft { persist(draft) }
    }

    func mutate(save: Bool = true, _ change: (inout CueDraft) -> Void) {
        guard !isWriteLocked, var draft, draft.trackUUID == row?.track.uuid else { return }
        change(&draft)
        self.draft = draft
        refreshSuggestions()
        if save { persist(draft) }
    }

    func persist(_ draft: CueDraft) {
        storage.saveCueDraft(draft)
        onCueDraftChange?(draft)
        onDraftChange?(draft.trackUUID, .cue, draft.hasChanges)
    }
}
