import Foundation

/// DJCrate 안에서 편집하는 큐. rekordbox에는 쓰지 않는다(검증된 반영 경로를 통해서만 나간다).
public struct EditableCue: Codable, Identifiable, Hashable, Sendable {
    public enum Kind: Codable, Hashable, Sendable {
        case memory
        /// 0…7 = A…H
        case hot(Int)

        public var slotLetter: String? {
            if case let .hot(slot) = self { return String(UnicodeScalar(UInt8(65 + slot))) }
            return nil
        }
    }

    /// 루프(rekordbox: 끝 지점 OutMsec, 활성 루프 ActiveLoop). 활성 루프는 곡을 불러오면 그 구간을 자동으로 반복한다.
    public struct Loop: Codable, Hashable, Sendable {
        /// 루프 끝(초, rekordbox 시간축)
        public var end: Double
        /// 활성 루프
        public var active: Bool
        /// 박 수(½박 = 0.5). nil = 박에 맞추지 않은 루프(rekordbox BeatLoopSize 0)
        public var beats: Double?

        public init(end: Double, active: Bool = false, beats: Double? = nil) {
            self.end = end; self.active = active; self.beats = beats
        }

        /// rekordbox `BeatLoopSize`(상위 16비트 = 분자, 하위 16비트 = 분모. 8박 = 8<<16|1, ½박 = 1<<16|2, 0 = 박 없음) → 박 수
        public static func beats(beatLoopSize value: Int) -> Double? {
            let numerator = value >> 16, denominator = value & 0xFFFF
            guard numerator > 0, denominator > 0 else { return nil }
            return Double(numerator) / Double(denominator)
        }

        /// 박 수 → rekordbox `BeatLoopSize`. 1박 이상은 정수, 1박 미만은 1/n만 쓴다. 나머지는 0(박 없음).
        public static func beatLoopSize(beats: Double?) -> Int {
            guard let beats, beats > 0 else { return 0 }
            if beats >= 1 {
                let whole = beats.rounded()
                return abs(beats - whole) < 0.001 && whole <= 0x7FFF ? Int(whole) << 16 | 1 : 0
            }
            let denominator = (1 / beats).rounded()
            return abs(1 / denominator - beats) < 0.0001 && denominator <= 0xFFFF ? 1 << 16 | Int(denominator) : 0
        }
    }

    public var id: UUID
    /// rekordbox `djmdCue.ID`. rekordbox에서 불러온 큐만 가진다.
    public var sourceID: String?
    public var kind: Kind
    public var time: Double
    public var name: String
    /// 루프면 끝 지점·활성 여부(옛 초안에는 없다)
    public var loop: Loop?

    public init(id: UUID = UUID(), sourceID: String? = nil, kind: Kind, time: Double, name: String = "", loop: Loop? = nil) {
        self.id = id
        self.sourceID = sourceID
        self.kind = kind
        self.time = time
        self.name = name
        self.loop = loop
    }

    /// 루프 길이(초)
    public var loopLength: Double? { loop.map { $0.end - time } }

    /// rekordbox 큐 → 편집용. Kind 매핑은 실측 분포 기반(1,2,3 → A,B,C / 5…9 → D…H).
    /// 자동 생성 이름과 의미 미확인 Kind(4)는 편집 대상에서 뺀다.
    public init?(_ cue: Cue) {
        let kind: Kind
        switch cue.kind {
        case 0: kind = .memory
        case 1, 2, 3: kind = .hot(cue.kind - 1)
        case 5...9: kind = .hot(cue.kind - 2)
        default: return nil
        }
        self.init(sourceID: cue.id, kind: kind, time: Double(cue.inMsec) / 1000,
                  name: cue.isAutoGenerated ? "" : cue.name,
                  loop: cue.isLoop ? Loop(end: Double(cue.outMsec) / 1000, active: cue.activeLoop > 0,
                                          beats: Loop.beats(beatLoopSize: cue.beatLoopSize)) : nil)
    }
}

/// 곡 하나의 큐 초안. `base`는 편집을 시작할 때의 rekordbox 상태다.
public struct CueDraft: Codable, Equatable, Sendable {
    public var trackUUID: String
    public var base: [EditableCue]
    public var cues: [EditableCue]

    public init(trackUUID: String, rekordboxCues: [Cue]) {
        self.trackUUID = trackUUID
        base = rekordboxCues.filter { !$0.isAutoGenerated }.compactMap(EditableCue.init).sorted { $0.time < $1.time }
        cues = base
    }

    public enum Change: Hashable, Sendable {
        case added(EditableCue)
        case removed(EditableCue)
        case modified(from: EditableCue, to: EditableCue)
    }

    /// rekordbox 상태(`base`) 대비 변경. 시각은 1ms 미만 차이를 무시한다.
    public var changes: [Change] {
        let current = Dictionary(uniqueKeysWithValues: cues.map { ($0.id, $0) })
        var result: [Change] = []
        for old in base {
            guard let new = current[old.id] else { result.append(.removed(old)); continue }
            if old.kind != new.kind || abs(old.time - new.time) >= 0.001 || old.name != new.name
                || old.loop?.active != new.loop?.active || abs((old.loop?.end ?? -1) - (new.loop?.end ?? -1)) >= 0.001
                || old.loop?.beats != new.loop?.beats {
                result.append(.modified(from: old, to: new))
            }
        }
        let baseIDs = Set(base.map(\.id))
        result += cues.filter { !baseIDs.contains($0.id) }.map(Change.added)
        return result
    }

    public var hasChanges: Bool { !changes.isEmpty }

    /// 같은 슬롯의 핫큐는 하나만. 새로 놓는 쪽이 이긴다(기존 것은 제거).
    public mutating func place(_ cue: EditableCue) {
        if case .hot = cue.kind { cues.removeAll { $0.kind == cue.kind && $0.id != cue.id } }
        if let index = cues.firstIndex(where: { $0.id == cue.id }) {
            cues[index] = cue
        } else {
            cues.append(cue)
        }
        cues.sort { $0.time < $1.time }
    }

    public mutating func remove(_ id: EditableCue.ID) {
        cues.removeAll { $0.id == id }
    }

    public mutating func revert() {
        cues = base
    }

    /// rekordbox로 내보내기 전 확인할 문제. 반영 경로 검증(V1) 때 기준을 확정한다.
    public func issues(duration: Double) -> [String] {
        var issues: [String] = []
        let slots = cues.compactMap(\.kind.slotLetter)
        if Set(slots).count != slots.count { issues.append(String(ui: "같은 핫큐 슬롯이 두 번 쓰였습니다")) }
        if cues.contains(where: { $0.time < 0 || $0.time > duration }) { issues.append(String(ui: "곡 길이를 벗어난 큐가 있습니다")) }
        return issues
    }
}

/// 초안은 곡 UUID별 JSON으로 Application Support에 둔다.
public extension CueDraft {
    /// 모든 큐(원본 포함)를 옮긴다. rekordbox 시간축 ↔ DJCrate 시간축 변환에 쓴다.
    func shifted(by seconds: Double) -> CueDraft {
        guard seconds != 0 else { return self }
        var copy = self
        copy.base = base.map { var cue = $0; cue.time += seconds; return cue }
        copy.cues = cues.map { var cue = $0; cue.time += seconds; return cue }
        return copy
    }
}
