import AnicueCore
import AVFoundation
import Foundation

let usage = """
    anicue — rekordbox 애니송 라이브러리 관리 도구 (읽기 전용 단계)

    사용법:
      anicue snapshot [--force]           rekordbox master.db 스냅샷 생성
      anicue report [--db PATH] [--files] 라이브러리 현황 (기본: 최신 스냅샷)
      anicue parse "<코멘트>"              코멘트 문법 파싱 결과 출력
      anicue analyze <파일|ContentID> [--db PATH]
                                          Music Understanding 파트 분석 (ContentID면 기존 큐와 비교)
      anicue mockup-data <ContentID> --out PATH [--db PATH]
                                          디자인 시안용 실데이터(JSON) 내보내기
      anicue grid-check [--limit N] [--db PATH]
                                          템포 구간으로 재생성한 그리드와 rekordbox 원본(PQTZ) 오차 측정
      anicue grid-estimate-eval [--limit N] [--db PATH]
                                      MU 박·마디로 추정한 그리드를 rekordbox 그리드와 비교
      anicue eval-cues [--limit N] [--db PATH]
                                          섹션 경계 메모리 큐 후보를 직접 찍은 큐와 비교 평가
    """

func clock(_ seconds: Double) -> String {
    String(format: "%d:%05.2f", Int(seconds) / 60, seconds.truncatingRemainder(dividingBy: 60))
}

func analyze(_ target: String, snapshotPath: String?) async throws {
    var url = URL(filePath: target)
    var track: Track?
    var cues: [Cue] = []
    if !FileManager.default.fileExists(atPath: target) {
        let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        guard let found = library.tracks.first(where: { $0.id == target }) else {
            print("트랙을 찾지 못했습니다: \(target)"); return
        }
        track = found
        cues = library.cues(for: found)
        url = URL(filePath: found.folderPath)
    }

    let started = Date()
    let analysis = try await PartAnalyzer.analyze(fileAt: url, cacheKey: track?.uuid)

    if let track { print("\(track.title) — \(track.artist ?? "")\n코멘트: \(track.comment)") }
    print(String(format: "길이 %@ · BPM %@ · 분석 %.1f초 · 통합 음량 %@ LUFS",
                 clock(analysis.duration),
                 analysis.bpm.map { String(format: "%.1f", $0) } ?? "-",
                 Date().timeIntervalSince(started),
                 analysis.integratedLoudness.map { String(format: "%.1f", $0) } ?? "-"))
    print("키: " + analysis.keys.map { "\(clock($0.span.start)) \($0.name)" }.joined(separator: " → "))
    print("마디 \(analysis.bars.count) · 섹션 \(analysis.sections.count) · 세그먼트 \(analysis.segments.count) · 프레이즈 \(analysis.phrases.count)\n")

    print("섹션별 에너지 (음량 LUFS / 보컬 / 드럼 / 점수)")
    for e in PartLabeler.energies(analysis) {
        print(String(format: "  %@–%@  %6.1f  %.2f  %.2f  %.2f",
                     clock(e.span.start), clock(e.span.end), e.loudness, e.vocal, e.drum, e.score))
    }

    print("\n파트 추정 v0")
    for m in PartLabeler.label(analysis) {
        print("  \(m.label.rawValue)\t\(clock(m.time))\t\(m.bar.map { "\($0)마디" } ?? "")\t신뢰도 \(m.confidence)")
    }

    if !cues.isEmpty {
        print("\nrekordbox 기존 큐 (직접 찍은 것)")
        for cue in cues.filter({ !$0.isAutoGenerated }).sorted(by: { $0.inMsec < $1.inMsec }) {
            let time = Double(cue.inMsec) / 1000
            let slot = cue.hotCueSlot.map { "핫큐 \($0)" } ?? "메모리"
            print("  \(slot)\t\(clock(time))\t\(analysis.barNumber(at: time).map { "\($0)마디" } ?? "")")
        }
    }
}

/// 직접 찍은 큐(자동 이름 제외)가 3개 이상인 로컬 곡을 UUID 순으로 뽑아 평가한다.
func evaluateCues(limit: Int, snapshotPath: String?) async throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    let sample = library.tracks
        .filter { !$0.isStreaming && FileManager.default.fileExists(atPath: $0.folderPath) }
        .filter { library.cues(for: $0).filter { !$0.isAutoGenerated }.count >= 3 }
        .sorted { $0.uuid < $1.uuid }
        .prefix(limit)

    var byBeat = CueEvaluation(), byQuarterSecond = CueEvaluation()
    var failures = 0
    var seconds: [Double] = []
    for (index, track) in sample.enumerated() {
        let started = Date()
        do {
            let analysis = try await PartAnalyzer.analyze(fileAt: URL(filePath: track.folderPath), cacheKey: track.uuid)
            seconds.append(Date().timeIntervalSince(started))
            // 같은 위치의 메모리 큐와 핫큐는 하나로 센다.
            var truth: [Double] = []
            for time in library.cues(for: track).filter({ !$0.isAutoGenerated }).map({ Double($0.inMsec) / 1000 }).sorted()
            where !truth.contains(where: { abs($0 - time) < 0.1 }) {
                truth.append(time)
            }
            let predicted = MemoryCueSuggester.candidates(analysis)
            let beat = analysis.bpm.map { 60 / $0 } ?? 0.4
            let e1 = CueEvaluation(truth: truth, predicted: predicted, tolerance: beat)
            let e2 = CueEvaluation(truth: truth, predicted: predicted, tolerance: 0.25)
            byBeat = byBeat + e1
            byQuarterSecond = byQuarterSecond + e2
            print(String(format: "%3d  재현 %2d/%-2d  정밀 %2d/%-2d  %4.1fs  %@",
                         index + 1, e1.truthMatched, e1.truth, e1.predictedMatched, e1.predicted,
                         seconds.last!, String(track.comment.prefix(40))))
        } catch {
            failures += 1
            print(String(format: "%3d  실패: %@", index + 1, String(describing: error)))
        }
    }

    let average = seconds.isEmpty ? 0 : seconds.reduce(0, +) / Double(seconds.count)
    print(String(format: "\n곡 %d (실패 %d) · 곡당 분석 평균 %.1f초", sample.count, failures, average))
    print(String(format: "±1박:    재현율 %.1f%% (%d/%d) · 정밀도 %.1f%% (%d/%d)",
                 byBeat.recall * 100, byBeat.truthMatched, byBeat.truth,
                 byBeat.precision * 100, byBeat.predictedMatched, byBeat.predicted))
    print(String(format: "±0.25초: 재현율 %.1f%% · 정밀도 %.1f%%",
                 byQuarterSecond.recall * 100, byQuarterSecond.precision * 100))
}

/// 디자인 시안에 넣을 실제 데이터. 앨범 커버 이미지는 넣지 않는다.
func exportMockupData(_ id: String, to out: URL, snapshotPath: String?) async throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    guard let track = library.tracks.first(where: { $0.id == id }) else { print("트랙 없음: \(id)"); return }
    let url = URL(filePath: track.folderPath)
    let analysis = try await PartAnalyzer.analyze(fileAt: url, cacheKey: track.uuid)
    let waveform = try WaveformAnalyzer.analyze(fileAt: url)
    let cues = library.cues(for: track).sorted { $0.inMsec < $1.inMsec }
    let hotA = cues.first { $0.hotCueSlot == "A" }.map { Double($0.inMsec) / 1000 } ?? 60
    let zoomStart = max(0, hotA - 12), zoomEnd = zoomStart + 24

    func row(_ t: Track) -> [String: Any] {
        let manual = library.cues(for: t).filter { !$0.isAutoGenerated }.count
        // 목록용 미니 개요 파형(160칸)과 큐 위치
        var mini: [String: Any] = [:]
        if !t.isStreaming, let w = try? WaveformAnalyzer.analyze(fileAt: URL(filePath: t.folderPath)).downsampled(to: 160) {
            mini = ["low": w.low, "mid": w.mid, "high": w.high, "duration": w.duration]
        }
        let cuePoints = library.cues(for: t).filter { !$0.isAutoGenerated }.map {
            ["time": Double($0.inMsec) / 1000, "slot": $0.hotCueSlot.map(String.init) ?? ""] as [String: Any]
        }
        return ["mini": mini, "cuePoints": cuePoints, "title": t.title, "artist": t.artist ?? "", "album": t.album ?? "", "comment": t.comment,
                "class": CommentClassifier.classify(t.comment).rawValue, "imported": t.importedOn ?? "",
                "plays": library.playCounts[t.id, default: 0], "bpm": t.bpm ?? 0, "key": t.key ?? "",
                "cues": library.cues(for: t).isEmpty ? "none" : (manual > 0 ? "manual \(manual)" : "auto"),
                "length": t.lengthSeconds]
    }
    // 목록: 선택 곡 + 규칙 코멘트 곡 + 2025~26 빈 코멘트 로컬 파일
    let local = library.tracks.filter { !$0.isStreaming }
    let convention = local.filter { CommentClassifier.classify($0.comment) == .convention && library.playCounts[$0.id, default: 0] > 3 }
        .sorted { $0.uuid < $1.uuid }.prefix(8)
    let backlog = local.filter { $0.comment.isEmpty && ["2025", "2026"].contains($0.importYear ?? "") }
        .sorted { $0.uuid < $1.uuid }.prefix(8)
    let parsed = ConventionParser.parse(track.comment)

    let energies = PartLabeler.energies(analysis)
    let lo = energies.map(\.score).filter(\.isFinite).min() ?? 0, hi = energies.map(\.score).filter(\.isFinite).max() ?? 1
    let overview = waveform.downsampled(to: 900)
    let zoom = waveform.slice(from: zoomStart, to: zoomEnd)
    let payload: [String: Any] = [
        "track": row(track).merging([
            "parsed": [
                "prefix": parsed?.prefix.rawValue ?? "", "work": parsed?.workName ?? "",
                "usage": parsed?.usages.map { $0.kind.rawValue + ($0.numbers.isEmpty ? "" : " " + $0.numbers.map(String.init).joined(separator: ",")) } ?? [],
            ],
            "duration": analysis.duration,
        ]) { a, _ in a },
        "library": [row(track)] + convention.map(row) + backlog.map(row),
        "counts": ["live": library.tracks.count, "backlog": backlog.count],
        "analysis": [
            "bpm": analysis.bpm ?? 0, "bars": analysis.bars.count,
            "key": analysis.keys.first?.name ?? "",
            "sections": energies.map { ["start": $0.span.start, "end": $0.span.end,
                                        "energy": hi > lo && $0.score.isFinite ? ($0.score - lo) / (hi - lo) : 0,
                                        "vocal": $0.vocal] },
            "barTimes": analysis.bars,
            "labels": PartLabeler.label(analysis).map { ["label": $0.label.rawValue, "time": $0.time] },
            "suggestions": MemoryCueSuggester.suggestions(analysis, existing: cues.map { Double($0.inMsec) / 1000 }),
        ],
        "cues": cues.map { ["slot": $0.hotCueSlot.map(String.init) ?? "", "time": Double($0.inMsec) / 1000,
                            "memory": $0.isMemoryCue, "auto": $0.isAutoGenerated] },
        "waveform": [
            "overview": ["rate": overview.rate, "low": overview.low, "mid": overview.mid, "high": overview.high],
            "zoom": ["start": zoomStart, "rate": zoom.rate, "low": zoom.low, "mid": zoom.mid, "high": zoom.high],
        ],
    ]
    let data = try JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys])
    try data.write(to: out)
    print("\(out.path) (\(data.count / 1024)KB) · 파형 \(waveform.count)칸 · 확대 \(Int(zoomStart))~\(Int(zoomEnd))초")
}

func gridCheck(limit: Int, snapshotPath: String?) throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    var errors: [Double] = [], segmentCounts: [Int: Int] = [:], checked = 0, mismatchedCount = 0
    for track in library.tracks.sorted(by: { $0.uuid < $1.uuid }).prefix(limit) {
        guard let url = RekordboxShare.analysisURL(track.analysisDataPath),
              let grid = try? BeatGrid.load(anlz: url), !grid.beats.isEmpty else { continue }
        let draft = GridDraft(trackUUID: track.uuid, grid: grid)
        let duration = Double(track.lengthSeconds) + 1
        let rebuilt = draft.grid(duration: max(duration, grid.beats.last!.time + 0.01))
        segmentCounts[draft.segments.count, default: 0] += 1
        checked += 1
        // 원본 박마다 가장 가까운 재생성 박과의 차이
        var worst = 0.0
        for beat in grid.beats {
            let nearest = rebuilt.snap(beat.time)
            worst = max(worst, abs(nearest - beat.time))
        }
        if rebuilt.beats.count != grid.beats.count { mismatchedCount += 1 }
        errors.append(worst * 1000)
        if worst > 0.01 { print("  큰 오차 \(Int(worst * 1000))ms · 구간 \(draft.segments.count) · \(track.title.prefix(30))") }
    }
    errors.sort()
    func pct(_ p: Double) -> Double { errors.isEmpty ? 0 : errors[min(errors.count - 1, Int(Double(errors.count - 1) * p))] }
    print("검사 \(checked)곡 · 구간 수 분포 \(segmentCounts.sorted { $0.key < $1.key })")
    print(String(format: "곡별 최대 오차(ms): 중앙값 %.2f · 95%% %.2f · 99%% %.2f · 최대 %.2f", pct(0.5), pct(0.95), pct(0.99), errors.last ?? 0))
    print("오차 ≤1ms 곡: \(errors.filter { $0 <= 1.0005 }.count) · ≤2ms: \(errors.filter { $0 <= 2.0005 }.count) · 박 개수 불일치 곡: \(mismatchedCount)")
}

/// MU 박·마디로 추정한 그리드를 rekordbox 그리드와 비교한다.
func evaluateGridEstimates(limit: Int, snapshotPath: String?) async throws {
    if let ratio = ProcessInfo.processInfo.environment["ANICUE_HALF"].flatMap(Double.init) { GridEstimator.halfBeatRatio = ratio }
    if let ratio = ProcessInfo.processInfo.environment["ANICUE_SINGLE"].flatMap(Double.init) { GridEstimator.singleSegmentRatio = ratio }
    if let spread = ProcessInfo.processInfo.environment["ANICUE_SPREAD"].flatMap(Double.init) { GridEstimator.tempoSpread = spread }
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    let playable = library.tracks.filter { !$0.isStreaming && FileManager.default.fileExists(atPath: $0.folderPath) }
    let withGrid = playable.filter { track in
        guard let url = RekordboxShare.analysisURL(track.analysisDataPath), let grid = try? BeatGrid.load(anlz: url) else { return false }
        return !grid.beats.isEmpty
    }
    print("재생 가능 \(playable.count)곡 · rekordbox 그리드 있음 \(withGrid.count) · 없음 \(playable.count - withGrid.count) · BPM 없음 \(playable.filter { ($0.bpm ?? 0) <= 0 }.count)")

    // 이미 분석 캐시가 있는 곡을 먼저 쓰고, 모자라면 uuid 순으로 채운다(표본이 매번 같게).
    let cached = Set((try? FileManager.default.contentsOfDirectory(atPath: PartAnalyzer.cacheDirectory.path)) ?? [])
        .compactMap { $0.split(separator: "-").first.map(String.init) }
    let sample = (withGrid.filter { cached.contains($0.uuid) } + withGrid.sorted { $0.uuid < $1.uuid })
        .reduce(into: [Track]()) { list, track in if !list.contains(where: { $0.id == track.id }) { list.append(track) } }
        .prefix(limit)

    var checked = 0, failed = 0, octave = 0, bpmClose = 0, gridOK = 0, downbeatOK = 0, confident = 0, confidentGridOK = 0
    var multiTruth = 0, multiEstimate = 0
    var diagMU = 0, diagAccent = 0, diagAccentLow = 0, diagCount = 0
    var oursBetter = 0, rbBetter = 0, tie = 0
    var bpmErrors: [Double] = []
    for track in sample {
        guard let anlz = RekordboxShare.analysisURL(track.analysisDataPath), let truthGrid = try? BeatGrid.load(anlz: anlz) else { continue }
        let analysis: PartAnalysis
        do { analysis = try await PartAnalyzer.analyze(fileAt: URL(filePath: track.folderPath), cacheKey: track.uuid) } catch { failed += 1; continue }
        let audioURL = URL(filePath: track.folderPath)
        let onset = ProcessInfo.processInfo.environment["ANICUE_NO_ONSET"] == nil ? try? OnsetEnvelope.compute(url: audioURL) : nil
        // 추정은 anicue 시간축, rekordbox 그리드는 rekordbox 시간축 → 형식 규칙으로 옮겨 비교한다.
        let timelineOffset = RekordboxTimeline.predictedOffset(url: audioURL)
        guard var estimate = GridEstimator.estimate(beats: analysis.beats, bars: analysis.bars, duration: analysis.duration, onset: onset) else {
            failed += 1
            print("  추정 실패 · 박 \(analysis.beats.count) · \(track.title.prefix(30))")
            continue
        }
        checked += 1
        for i in estimate.segments.indices { estimate.segments[i].start += timelineOffset }
        let truth = GridDraft.segments(from: truthGrid)
        if truth.count > 1 { multiTruth += 1 }
        if estimate.segments.count > 1 { multiEstimate += 1 }
        let grid = GridDraft(trackUUID: track.uuid, base: [], segments: estimate.segments).grid(duration: analysis.duration + 1)
        let ratio = estimate.bpm / truth[0].bpm
        if abs(ratio - 2) < 0.02 || abs(ratio - 0.5) < 0.01 { octave += 1 }
        let error = abs(estimate.bpm - truth[0].bpm)
        bpmErrors.append(error)
        if error < 0.05 { bpmClose += 1 }

        // 곡 앞뒤 10%를 뺀 rekordbox 박마다 가장 가까운 추정 박과의 거리, 1박 일치
        let lo = analysis.duration * 0.1, hi = analysis.duration * 0.9
        var distances: [Double] = [], downbeats = 0, downbeatHits = 0
        for beat in truthGrid.beats where beat.time >= lo && beat.time <= hi {
            guard let nearest = nearestBeat(grid, to: beat.time) else { continue }
            distances.append(abs(nearest.time - beat.time) * 1000)
            if beat.number == 1 {
                downbeats += 1
                if nearest.number == 1 { downbeatHits += 1 }
            }
        }
        distances.sort()
        let p90 = distances.isEmpty ? .infinity : distances[Int(Double(distances.count - 1) * 0.9)]
        let aligned = p90 <= 20
        let downbeatRate = downbeats > 0 ? Double(downbeatHits) / Double(downbeats) : 0
        if aligned { gridOK += 1 }
        if aligned && downbeatRate >= 0.9 { downbeatOK += 1 }
        if estimate.isConfident {
            confident += 1
            if aligned { confidentGridOK += 1 }
        }
        if ProcessInfo.processInfo.environment["ANICUE_DIAG"] != nil, let onset, let first = grid.beats.first {
            // 1박 어긋남(칸) · 반 박 비율(저역·전체)
            var deltas = [0, 0, 0, 0]
            for beat in truthGrid.beats where beat.number == 1 && beat.time >= lo && beat.time <= hi {
                if let nearest = nearestBeat(grid, to: beat.time) { deltas[(nearest.number - 1 + 4) % 4] += 1 }
            }
            let period = 60 / estimate.bpm
            let times = grid.beats.map { $0.time - timelineOffset }.filter { $0 > first.time - timelineOffset }
            let on = times.reduce(0.0) { $0 + Double(onset.value(at: $1)) }, off = times.reduce(0.0) { $0 + Double(onset.value(at: $1 + period / 2)) }
            let onLow = times.reduce(0.0) { $0 + Double(onset.lowValue(at: $1)) }, offLow = times.reduce(0.0) { $0 + Double(onset.lowValue(at: $1 + period / 2)) }
            // 박 번호별 어택 합: 가장 센 번호를 1박으로 보면 rekordbox와 맞는가
            var accent = [0.0, 0.0, 0.0, 0.0], accentLow = [0.0, 0.0, 0.0, 0.0]
            for beat in grid.beats {
                accent[beat.number - 1] += Double(onset.value(at: beat.time - timelineOffset))
                accentLow[beat.number - 1] += Double(onset.lowValue(at: beat.time - timelineOffset))
            }
            let rbNumber = (deltas.indices.max { deltas[$0] < deltas[$1] } ?? 0) + 1
            let accentNumber = (accent.indices.max { accent[$0] < accent[$1] } ?? 0) + 1
            let accentLowNumber = (accentLow.indices.max { accentLow[$0] < accentLow[$1] } ?? 0) + 1
            if aligned { diagMU += rbNumber == 1 ? 1 : 0; diagAccent += rbNumber == accentNumber ? 1 : 0; diagAccentLow += rbNumber == accentLowNumber ? 1 : 0; diagCount += 1 }
            print(String(format: "  [진단] %@ · rb 1박에 놓인 우리 박 번호 분포 %@ · 어택최대 %d 저역최대 %d · 반박/정박 %.2f · %@",
                         aligned ? "박맞음" : (p90 > period * 1000 * 0.35 ? "반박?" : "어긋남"), deltas.description, accentNumber, accentLowNumber, off / max(on, 1e-9), String(track.title.prefix(20))))
        }
        if ProcessInfo.processInfo.environment["ANICUE_VERBOSE"] != nil {
            // 부호 있는 차이(추정 - rekordbox), 박 간격으로 접어서 본다.
            let period = 60 / truth[0].bpm
            var signed: [Double] = []
            for beat in truthGrid.beats where beat.time >= lo && beat.time <= hi {
                guard let nearest = nearestBeat(grid, to: beat.time) else { continue }
                var d = (nearest.time - beat.time).truncatingRemainder(dividingBy: period)
                if d > period / 2 { d -= period } else if d < -period / 2 { d += period }
                signed.append(d * 1000)
            }
            signed.sort()
            let ext = (track.folderPath as NSString).pathExtension.lowercased()
            print(String(format: "  [상세] %@ · 차이 중앙값 %+.1fms · rb %.2f 추정 %.2f · %@", ext, signed.isEmpty ? 0 : signed[signed.count / 2],
                         truth[0].bpm, estimate.bpm, String(track.title.prefix(24))))
        }
        if !aligned, let onset {
            // 어긋난 곡: 실제 어택에 더 잘 맞는 쪽은? (박 위치의 평균 어택)
            let rbScore = truthGrid.beats.reduce(0.0) { $0 + Double(onset.value(at: $1.time - timelineOffset)) } / Double(truthGrid.beats.count)
            let ours = grid.beats.filter { $0.time >= truthGrid.beats[0].time }
            let ourScore = ours.reduce(0.0) { $0 + Double(onset.value(at: $1.time - timelineOffset)) } / Double(max(ours.count, 1))
            if ourScore > rbScore * 1.05 { oursBetter += 1 } else if rbScore > ourScore * 1.05 { rbBetter += 1 } else { tie += 1 }
        }
        if !aligned || downbeatRate < 0.9 {
            print(String(format: "  %@ · rb %.2f(%d구간) · 추정 %.2f(%d구간) · p90 %.0fms · 1박 %.0f%% · 잔차 %.1fms · 적합 %.0f%% · %@",
                         aligned ? "1박만 틀림" : "어긋남", truth[0].bpm, truth.count, estimate.bpm, estimate.segments.count,
                         p90, downbeatRate * 100, estimate.medianResidualMs, estimate.inlierRatio * 100, String(track.title.prefix(28))))
        }
    }
    bpmErrors.sort()
    func pct(_ p: Double) -> Double { bpmErrors.isEmpty ? 0 : bpmErrors[Int(Double(bpmErrors.count - 1) * p)] }
    print("비교 \(checked)곡(실패 \(failed)) · rekordbox 변속곡 \(multiTruth) · 추정 변속곡 \(multiEstimate)")
    print(String(format: "BPM 오차 중앙값 %.3f · 90%% %.3f · ±0.05 안 %d곡 · 두 배/절반 %d곡", pct(0.5), pct(0.9), bpmClose, octave))
    if diagCount > 0 { print("[진단] 박 맞은 \(diagCount)곡에서 1박 일치: MU 마디 \(diagMU) · 어택 최대 \(diagAccent) · 저역 어택 최대 \(diagAccentLow)") }
    print("어긋난 곡에서 실제 어택에 더 잘 맞는 쪽: anicue \(oursBetter) · rekordbox \(rbBetter) · 비슷 \(tie)")
    print("박 위치 일치(90%가 20ms 안) \(gridOK)곡 · 1박까지 일치 \(downbeatOK)곡 · 자신 있는 추정 \(confident)곡 중 박 일치 \(confidentGridOK)")
}

/// rekordbox 파형과 anicue 디코딩을 맞대어 파일별 시간축 차이를 재고, 프라이밍 정보와 비교한다.
func timelineCheck(limit: Int, snapshotPath: String?) throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    // 형식이 고루 섞이게 확장자별로 번갈아 뽑는다.
    let candidates = library.tracks.filter { !$0.isStreaming && FileManager.default.fileExists(atPath: $0.folderPath) }
        .sorted { $0.uuid < $1.uuid }
    let byExt = Dictionary(grouping: candidates) { ($0.folderPath as NSString).pathExtension.lowercased() }
    var sample: [Track] = []
    var cursors = byExt.mapValues { _ in 0 }
    while sample.count < limit, cursors.contains(where: { byExt[$0.key]!.count > $0.value }) {
        for ext in byExt.keys.sorted() where sample.count < limit {
            let i = cursors[ext]!
            if i < byExt[ext]!.count { sample.append(byExt[ext]![i]); cursors[ext] = i + 1 }
        }
    }
    var rows: [(ext: String, offset: Double, corr: Double, priming: Int, remainder: Int, rate: Double, format: String)] = []
    var predictions: [(String, Double, Double, Double)] = []
    var waves: [(ext: String, offset: Double, corr: Double, predicted: Double, header: String)] = []
    for track in sample {
        guard let dat = RekordboxShare.analysisURL(track.analysisDataPath),
              let grid = try? BeatGrid.load(anlz: dat), grid.beats.count > 32 else { continue }
        let url = URL(filePath: track.folderPath)
        guard let onset = try? OnsetEnvelope.compute(url: url) else { continue }
        // rekordbox 박을 lag만큼 당겼을 때 anicue 디코딩의 어택과 가장 잘 겹치는 lag(그리드 기준)
        let best = onset.bestLag(for: grid.beats.map(\.time), range: -0.12...0.12)
        // rekordbox 파형과 맞댄 순수한 시간축 차이(그리드 무관)
        let heights = (try? RekordboxTimeline.detailWaveform(ext: RekordboxTimeline.extURL(forAnalysis: dat))) ?? []
        let wave = heights.isEmpty ? nil : try? RekordboxTimeline.measureOffset(audio: url, rekordboxHeights: heights)
        waves.append((ext: (track.folderPath as NSString).pathExtension.lowercased(), offset: (wave?.offset ?? .nan) * 1000,
                      corr: wave?.correlation ?? 0, predicted: RekordboxTimeline.predictedOffset(url: url) * 1000,
                      header: (track.folderPath as NSString).pathExtension.lowercased() == "mp3" ? RekordboxTimeline.mp3Header(url: url) : ""))
        let info = RekordboxTimeline.packetInfo(url: url)
        let row = (ext: (track.folderPath as NSString).pathExtension.lowercased(), offset: best.lag * 1000,
                   corr: best.sharpness, priming: info?.primingFrames ?? -1, remainder: info?.remainderFrames ?? -1,
                   rate: info?.sampleRate ?? 0, format: info?.formatID ?? "?")
        rows.append(row)
        let predicted = RekordboxTimeline.predictedOffset(url: url) * 1000
        predictions.append((row.ext, row.offset, predicted, row.corr))
        if ProcessInfo.processInfo.environment["ANICUE_VERBOSE"] != nil || (row.corr >= 1.5 && abs(row.offset - predicted) > 5) {
            let header = row.ext == "mp3" ? RekordboxTimeline.mp3Header(url: url)
                : ["m4a", "mp4", "aac"].contains(row.ext) ? RekordboxTimeline.mp4Header(url: url) : ""
            print(String(format: "  %@ %@ · 실측 %+6.1fms · 예측 %+5.1fms · 선명도 %.2f · 프라이밍 %d 패딩 %d · %.0fHz · %@ · %@",
                         row.ext, row.format, row.offset, predicted, row.corr, row.priming, row.remainder, row.rate, header, String(track.title.prefix(20))))
        }
    }
    print("\n[파형 실측] 형식별 예측 적중(상관 0.8 이상, ±3ms 안)")
    for (ext, group) in Dictionary(grouping: waves.filter { $0.corr >= 0.8 }, by: \.ext).sorted(by: { $0.key < $1.key }) {
        let hits = group.filter { abs($0.offset - $0.predicted) <= 3 }.count
        let sorted = group.map(\.offset).sorted()
        print(String(format: "  %@: %d/%d · 실측 중앙값 %+.1fms (범위 %+.1f~%+.1f)", ext, hits, group.count, sorted[sorted.count / 2], sorted.first!, sorted.last!))
        for miss in group where abs(miss.offset - miss.predicted) > 3 {
            print(String(format: "    빗나감 실측 %+.1f · 예측 %+.1f · 상관 %.2f %@", miss.offset, miss.predicted, miss.corr, miss.header))
        }
    }
    print("  상관 낮아 제외: \(waves.filter { $0.corr < 0.8 }.count)곡")
    print("\n[그리드 기준] 예측 적중(선명도 1.5 이상, ±5ms 안)")
    for (ext, group) in Dictionary(grouping: predictions.filter { $0.3 >= 1.5 }, by: \.0).sorted(by: { $0.key < $1.key }) {
        let hits = group.filter { abs($0.1 - $0.2) <= 5 }.count
        print("  \(ext): \(hits)/\(group.count)")
    }
    let reliable = predictions.filter { $0.3 >= 1.5 }
    print("  전체: \(reliable.filter { abs($0.1 - $0.2) <= 5 }.count)/\(reliable.count) · 선명도 낮아 제외 \(predictions.count - reliable.count)")
    print("\n형식별 요약 (선명도 1.5 이상)")
    for (ext, group) in Dictionary(grouping: rows.filter { $0.corr >= 1.5 }, by: \.ext).sorted(by: { $0.key < $1.key }) {
        let diffs = group.map { $0.offset - (Double($0.priming) / max($0.rate, 1) * 1000) }.sorted()
        let offsets = group.map(\.offset).sorted()
        print(String(format: "  %@ %d곡 · 차이 중앙값 %+.1fms (범위 %+.1f~%+.1f) · 차이-프라이밍 중앙값 %+.1fms (범위 %+.1f~%+.1f)",
                     ext, group.count, offsets[offsets.count / 2], offsets.first!, offsets.last!,
                     diffs[diffs.count / 2], diffs.first!, diffs.last!))
    }
}

func nearestBeat(_ grid: BeatGrid, to time: Double) -> BeatGrid.Beat? {
    let i = grid.firstIndex(atOrAfter: time)
    let candidates = [i - 1, i].filter { grid.beats.indices.contains($0) }.map { grid.beats[$0] }
    return candidates.min { abs($0.time - time) < abs($1.time - time) }
}

func value(after flag: String, in args: [String]) -> String? {
    guard let i = args.firstIndex(of: flag), i + 1 < args.count else { return nil }
    return args[i + 1]
}

func run() async throws {
    let args = Array(CommandLine.arguments.dropFirst())
    switch args.first {
    case "snapshot":
        let url = try LibrarySnapshot.take(force: args.contains("--force"))
        print(url.path)

    case "report":
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        print("스냅샷: \(snapshot.path)\n")
        print(LibraryReport(library: library, checkFiles: args.contains("--files")).render())

    case "analyze":
        guard args.count > 1 else { print(usage); return }
        try await analyze(args[1], snapshotPath: value(after: "--db", in: args))

    case "mockup-data":
        guard args.count > 1, let out = value(after: "--out", in: args) else { print(usage); return }
        try await exportMockupData(args[1], to: URL(filePath: out), snapshotPath: value(after: "--db", in: args))

    case "bench-load":
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let clock = ContinuousClock()
        var library: RekordboxLibrary!
        let tLoad = try clock.measure { library = try RekordboxLibrary.load(snapshot: snapshot) }
        var classified = 0
        let tClassify = clock.measure { for t in library.tracks { if CommentClassifier.classify(t.comment) == .convention { classified += 1 } } }
        let tParse = clock.measure { for t in library.tracks { _ = ConventionParser.parse(t.comment) } }
        let tReport = clock.measure { _ = LibraryReport(library: library) }
        let tTree = clock.measure { _ = PlaylistNode.tree(library.playlists) }
        print("DB 읽기 \(tLoad) · 분류 \(tClassify) · 파싱 \(tParse) · 현황 집계 \(tReport) · 플레이리스트 트리 \(tTree) · 곡 \(library.tracks.count)")

    case "bench-waveform":
        guard args.count > 1 else { return }
        let clock = ContinuousClock()
        var w: Waveform!
        let t = try clock.measure { w = try WaveformAnalyzer.analyze(fileAt: URL(filePath: args[1])) }
        print("파형 \(t) · \(w.count)칸 · \(Int(w.duration))초")
        if let out = value(after: "--out", in: args) { try JSONEncoder().encode(w).write(to: URL(filePath: out)) }

    case "parity-check":
        // 정규식 파서(이전)와 새 파서를 실제 라이브러리 전체 코멘트로 비교한다.
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        var parseDiff = 0, classDiff = 0, checked = 0
        for comment in Set(library.allTracks.map(\.comment)) {
            checked += 1
            let old = RegexConventionParser.parse(comment), new = ConventionParser.parse(comment)
            if old != new {
                parseDiff += 1
                if parseDiff <= 12 { print("파싱 차이: \(comment)\n  이전 \(String(describing: old))\n  새것 \(String(describing: new))") }
            }
            let oldClass = RegexCommentClassifier.classify(comment), newClass = CommentClassifier.classify(comment)
            if oldClass != newClass {
                classDiff += 1
                if classDiff <= 12 { print("분류 차이: \(comment) · 이전 \(oldClass) · 새것 \(newClass)") }
            }
        }
        print("고유 코멘트 \(checked)개 · 파싱 차이 \(parseDiff) · 분류 차이 \(classDiff)")

    case "grid-check":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 500
        try gridCheck(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "grid-estimate-eval":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 40
        try await evaluateGridEstimates(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "grid":
        // 제목으로 rekordbox 그리드 앞부분과 형식별 시간축 차이를 본다(개발용).
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        guard args.count > 1 else { return }
        for track in library.tracks where track.title.contains(args[1]) && !track.isStreaming {
            guard let dat = RekordboxShare.analysisURL(track.analysisDataPath), let grid = try? BeatGrid.load(anlz: dat) else { continue }
            let offset = RekordboxTimeline.predictedOffset(url: URL(filePath: track.folderPath))
            let head = grid.beats.prefix(3).map { String(format: "%.3f(%d박)", $0.time, $0.number) }.joined(separator: " ")
            print(String(format: "%@ · %.2f BPM · 시간축 차이 %.1fms · 앞 박 %@", (track.folderPath as NSString).lastPathComponent, grid.beats.first?.bpm ?? 0, offset * 1000, head))
        }

    case "uncached":
        // 분석 캐시가 없는 로컬 곡 ContentID(개발용)
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        let cached = Set((try? FileManager.default.contentsOfDirectory(atPath: PartAnalyzer.cacheDirectory.path)) ?? [])
            .compactMap { $0.split(separator: "-").first.map(String.init) }
        let skip = Int(value(after: "--skip", in: args) ?? "") ?? 0
        let candidates = library.tracks.sorted(by: { $0.uuid > $1.uuid }).filter { !$0.isStreaming && !cached.contains($0.uuid)
            && FileManager.default.fileExists(atPath: $0.folderPath) && ["mp3", "m4a"].contains($0.fileExtension) }
        if candidates.indices.contains(skip) { print("\(candidates[skip].id)\t\(candidates[skip].title)") }

    case "import-check-sim":
        // 가져오기 흉내: 라이브러리 곡을 "추가한 곡"으로 보고 추정 그리드(보낼 값)를 rekordbox 그리드와 비교한다.
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        guard args.count > 1 else { return }
        for track in library.tracks where track.title.contains(args[1]) && !track.isStreaming {
            let url = URL(filePath: track.folderPath)
            guard var estimate = try await GridSuggestion.estimate(fileAt: url, cacheKey: track.uuid) else { continue }
            let offset = RekordboxTimeline.predictedOffset(url: url)
            for i in estimate.segments.indices { estimate.segments[i].start += offset }
            let imported = RekordboxShare.analysisURL(track.analysisDataPath).flatMap { try? BeatGrid.load(anlz: $0) }
            let check = StagedTrack.ImportCheck.compare(sent: estimate.segments, imported: imported,
                                                        duration: Double(track.lengthSeconds), checkedOn: "sim")
            print(String(format: "%@ · 보낼 %.2f BPM · rekordbox %.2f · 결과 %@ · 최대 차이 %.1fms",
                         (track.folderPath as NSString).lastPathComponent, estimate.bpm, check.rekordboxBPM ?? 0,
                         check.result.rawValue, check.maxDeviationMs ?? -1))
        }

    case "cue-columns":
        // djmdCue 칸 구성과 종류별 예시(개발용, 스냅샷 읽기 전용)
        let snapshot = try LibrarySnapshot.latest()
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        try db.query("PRAGMA table_info(djmdCue)") { row in print("  칸", row.string(1) ?? "", row.string(2) ?? "") }
        try db.query("""
            SELECT Kind, count(*), sum(OutMsec > 0), sum(ifnull(Color, -1) >= 0), sum(ifnull(ColorTableIndex, 0) > 0),
                   sum(length(ifnull(Comment, '')) > 0), sum(ifnull(ActiveLoop, 0) > 0)
            FROM djmdCue WHERE rb_local_deleted = 0 GROUP BY Kind ORDER BY Kind
            """) { row in
            print("  Kind \(row.int(0) ?? -1): \(row.int(1) ?? 0)개 · 루프(OutMsec>0) \(row.int(2) ?? 0) · Color \(row.int(3) ?? 0) · ColorTableIndex \(row.int(4) ?? 0) · 이름 \(row.int(5) ?? 0) · ActiveLoop \(row.int(6) ?? 0)")
        }
        try db.query("""
            SELECT Kind = 0, ifnull(Color, -1), ifnull(ColorTableIndex, -1), count(*) FROM djmdCue WHERE rb_local_deleted = 0
            GROUP BY 1, 2, 3 ORDER BY 1, 4 DESC LIMIT 30
            """) { row in print("  \(row.int(0) == 1 ? "메모리" : "핫큐") Color \(row.int(1) ?? -9) · ColorTableIndex \(row.int(2) ?? -9) · \(row.int(3) ?? 0)개") }
        try db.query("""
            SELECT Kind, InMsec, OutMsec, Color, ColorTableIndex, Comment, ActiveLoop, BeatLoopSize, InFrame, InMpegFrame
            FROM djmdCue WHERE rb_local_deleted = 0 AND OutMsec > 0 LIMIT 3
            """) { row in print("  루프 예:", (Int32(0)..<10).map { row.string($0) ?? "nil" }.joined(separator: " | ")) }

    case "reflection-dry-run":
        // 실제 초안으로 반영 계획을 만들어 보고 XML을 지정한 곳에만 쓴다(rekordbox는 건드리지 않는다).
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        let uuids = CueDraftStore.uuids().union(GridDraftStore.uuids())
        var plans: [Reflection.Plan] = []
        for track in library.tracks where uuids.contains(track.uuid) {
            let plan = Reflection.plan(track: track, rawCues: library.cues(for: track),
                                       cueDraft: CueDraftStore.load(trackUUID: track.uuid),
                                       gridDraft: GridDraftStore.load(trackUUID: track.uuid))
            plans.append(plan)
            let draft = CueDraftStore.load(trackUUID: track.uuid)
            print("• \(track.title.prefix(30)) · 큐 변경 \(draft?.changes.count ?? 0) · 그리드 변경 \(plan.gridChanged) · 표시 \(plan.beforeMarks.count)→\(plan.marks.count) · " +
                  (plan.isEligible ? "반영 가능" : plan.blockers.isEmpty ? "변경 없음" : "막힘: \(plan.blockers.joined(separator: " / "))"))
        }
        if let out = value(after: "--out", in: args) {
            try Reflection.document(plans: plans.filter(\.isEligible), playlistName: "anicue 반영 시험").write(toFile: out, atomically: true, encoding: .utf8)
            print("XML: \(out)")
        }

    case "write-probe":
        // 직접 쓰기 설계를 위한 읽기 전용 조사(스냅샷 사본)
        let snapshot = try LibrarySnapshot.latest()
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        try db.query("SELECT name FROM sqlite_master WHERE type='table' AND (name LIKE '%Cue%' OR name LIKE '%egistry%' OR name LIKE 'content%')") { print("표:", $0.string(0) ?? "") }
        try db.query("SELECT registry_id, id_1, id_2, int_1, int_2, str_1, date_1 FROM agentRegistry") { r in
            print("  agentRegistry", (Int32(0)..<7).map { r.string($0) ?? "nil" }.joined(separator: " | "))
        }
        try db.query("SELECT rb_local_deleted, count(*) FROM djmdCue GROUP BY 1") { print("  djmdCue 삭제표시", $0.int(0) ?? -1, $0.int(1) ?? 0) }
        try db.query("SELECT max(rb_local_usn), max(usn) FROM djmdCue") { print("  djmdCue 최대 usn", $0.string(0) ?? "", $0.string(1) ?? "") }
        try db.query("PRAGMA table_info(contentCue)") { print("  contentCue 칸", $0.string(1) ?? "", $0.string(2) ?? "") }
        if args.count > 1 {
            let id = args[1]
            try db.query("SELECT * FROM djmdCue WHERE ContentID = '\(id)' AND rb_local_deleted = 0 ORDER BY InMsec LIMIT 4") { r in
                print("  큐 행:", (Int32(0)..<29).map { r.string($0) ?? "nil" }.joined(separator: " | "))
            }
            try db.query("SELECT * FROM contentCue WHERE ContentID = '\(id)'") { r in
                print("  contentCue:", (Int32(0)..<12).map { String((r.string($0) ?? "nil").prefix(700)) }.joined(separator: " | "))
            }
            try db.query("SELECT ID, FileType, SampleRate, BitRate, BPM, AnalysisDataPath, rb_local_usn, usn, updated_at FROM djmdContent WHERE ID = '\(id)'") { r in
                print("  content:", (Int32(0)..<9).map { r.string($0) ?? "nil" }.joined(separator: " | "))
            }
        }

    case "cue-consistency":
        // djmdCue 행과 contentCue JSON이 같은지, JSON에 어떤 칸이 들어가는지(읽기 전용)
        let snapshot = try LibrarySnapshot.latest()
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        var rowsByContent: [String: [String: (Int, Int, Int)]] = [:]
        try db.query("SELECT ContentID, ID, InMsec, Kind, OutMsec FROM djmdCue WHERE rb_local_deleted = 0") { r in
            rowsByContent[r.string(0) ?? "", default: [:]][r.string(1) ?? ""] = (r.int(2) ?? 0, r.int(3) ?? 0, r.int(4) ?? 0)
        }
        var keys: [String: Int] = [:], same = 0, differ = 0, samples: [String] = [], countMismatch = 0, total = 0
        var withName = "", withColor = "", withLoop = ""
        try db.query("SELECT ContentID, Cues, rb_cue_count, rb_local_deleted FROM contentCue") { r in
            guard r.int(3) == 0 else { return }
            total += 1
            let id = r.string(0) ?? ""
            guard let data = r.string(1)?.data(using: .utf8),
                  let array = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else { return }
            if array.count != (r.int(2) ?? -1) { countMismatch += 1 }
            var json: [String: (Int, Int, Int)] = [:]
            for cue in array {
                for k in cue.keys { keys[k, default: 0] += 1 }
                json["\(cue["ID"] ?? "")"] = ((cue["InMsec"] as? Int) ?? 0, (cue["Kind"] as? Int) ?? 0, (cue["OutMsec"] as? Int) ?? 0)
                if withName.isEmpty, let c = cue["Comment"] as? String, !c.isEmpty { withName = String(describing: cue) }
                if withColor.isEmpty, let c = cue["ColorTableIndex"] as? Int, c > 0 { withColor = String(describing: cue) }
                if withLoop.isEmpty, let o = cue["OutMsec"] as? Int, o > 0 { withLoop = String(describing: cue) }
            }
            let db = rowsByContent[id] ?? [:]
            let matches = json.count == db.count && json.allSatisfy { entry in
                guard let row = db[entry.key] else { return false }
                return row.0 == entry.value.0 && row.1 == entry.value.1 && row.2 == entry.value.2
            }
            if matches { same += 1 } else {
                differ += 1
                if samples.count < 3 { samples.append("\(id): JSON \(json.count)개 · 행 \(db.count)개") }
            }
        }
        print("contentCue \(total)곡 · 행과 같음 \(same) · 다름 \(differ) · rb_cue_count 불일치 \(countMismatch)")
        print("다른 예:", samples)
        print("contentCue만 있고 행 없는 곡 수:", rowsByContent.count)
        print("JSON 칸:", keys.sorted { $0.value > $1.value }.map { "\($0.key) \($0.value)" }.joined(separator: ", "))
        print("이름 있는 예:", withName.prefix(600))
        print("색 있는 예:", withColor.prefix(600))
        print("루프 예:", withLoop.prefix(600))

    case "cue-fields":
        // rb_cue_count의 뜻과 MP3 큐의 MPEG 칸(읽기 전용)
        let snapshot = try LibrarySnapshot.latest()
        let db = try CipherDatabase(path: snapshot.path, key: RekordboxKey.derive())
        var tallies: [String: Int] = [:]
        try db.query("""
            SELECT cc.rb_cue_count,
                   (SELECT count(*) FROM djmdCue c WHERE c.ContentID = cc.ContentID),
                   (SELECT count(*) FROM djmdCue c WHERE c.ContentID = cc.ContentID AND c.Kind = 0),
                   (SELECT count(*) FROM djmdCue c WHERE c.ContentID = cc.ContentID AND c.Kind > 0),
                   cc.rb_local_synced, cc.rb_data_status
            FROM contentCue cc WHERE cc.rb_local_deleted = 0
            """) { r in
            let n = r.int(0) ?? -1, all = r.int(1) ?? 0, memory = r.int(2) ?? 0, hot = r.int(3) ?? 0
            let label = n == all ? "전체와 같음" : n == memory ? "메모리 수" : n == hot ? "핫큐 수" : n == 0 ? "0" : "기타"
            tallies["rb_cue_count=\(label) · synced \(r.int(4) ?? -1) · status \(r.int(5) ?? -1)", default: 0] += 1
        }
        for (k, v) in tallies.sorted(by: { $0.value > $1.value }).prefix(12) { print("  \(k): \(v)") }
        try db.query("""
            SELECT c.InMsec, c.InFrame, c.InMpegFrame, c.InMpegAbs, c.OutMsec, c.OutFrame, c.OutMpegFrame, c.OutMpegAbs,
                   c.InPointSeekInfo, c.CueMicrosec, t.FileType, t.SampleRate, t.BitRate
            FROM djmdCue c JOIN djmdContent t ON t.ID = c.ContentID
            WHERE t.FileType = 1 AND (c.InMpegFrame != 0 OR c.InPointSeekInfo IS NOT NULL) LIMIT 5
            """) { r in print("  MP3 큐:", (Int32(0)..<13).map { String((r.string($0) ?? "nil").prefix(80)) }.joined(separator: " | ")) }
        try db.query("SELECT t.FileType, count(*), sum(c.InMpegFrame != 0), sum(c.InPointSeekInfo IS NOT NULL) FROM djmdCue c JOIN djmdContent t ON t.ID = c.ContentID GROUP BY 1") { r in
            print("  파일 종류 \(r.int(0) ?? -1): 큐 \(r.int(1) ?? 0) · MpegFrame≠0 \(r.int(2) ?? 0) · SeekInfo \(r.int(3) ?? 0)")
        }
        try db.query("SELECT InMsec, InFrame FROM djmdCue LIMIT 20000") { r in
            let ms = r.int(0) ?? 0, frame = r.int(1) ?? 0
            let floorMatch = frame == ms * 150 / 1000, roundMatch = frame == Int((Double(ms) * 0.15).rounded())
            tallies["InFrame: floor \(floorMatch) round \(roundMatch)", default: 0] += 1
        }
        for (k, v) in tallies where k.hasPrefix("InFrame") { print("  \(k): \(v)") }

    case "db-diff":
        // 두 스냅샷 사본의 모든 표를 행·칸 단위로 비교한다(읽기 전용). 민감할 수 있는 값은 가린다.
        guard args.count > 2 else { print("anicue db-diff <전.db> <후.db>"); return }
        let key = try RekordboxKey.derive()
        let before = try CipherDatabase(path: args[1], key: key), after = try CipherDatabase(path: args[2], key: key)
        var tables: [String] = []
        try after.query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name") { tables.append($0.string(0) ?? "") }
        func sensitive(_ table: String, _ column: String, _ rowKey: String) -> Bool {
            let text = (table + column + rowKey).lowercased()
            return ["credential", "token", "password", "secret", "auth", "session"].contains { text.contains($0) }
        }
        for table in tables {
            var columns: [String] = [], pk: [Int] = []
            try after.query("PRAGMA table_info(\(table))") { r in
                columns.append(r.string(1) ?? "")
                if (r.int(5) ?? 0) > 0 { pk.append(columns.count - 1) }
            }
            let keyColumns = pk.isEmpty ? (columns.firstIndex(of: "ID").map { [$0] } ?? []) : pk
            func load(_ db: CipherDatabase) throws -> [String: [String?]] {
                var rows: [String: [String?]] = [:]
                let select = "SELECT " + (keyColumns.isEmpty ? "rowid, " : "") + columns.map { "\"\($0)\"" }.joined(separator: ", ") + " FROM \(table)"
                try db.query(select) { r in
                    let offset: Int32 = keyColumns.isEmpty ? 1 : 0
                    let values = (0..<columns.count).map { r.string(Int32($0) + offset) }
                    let rowKey = keyColumns.isEmpty ? (r.string(0) ?? "") : keyColumns.map { values[$0] ?? "nil" }.joined(separator: "/")
                    rows[rowKey] = values
                }
                return rows
            }
            let a = (try? load(before)) ?? [:], b = try load(after)
            let added = b.keys.filter { a[$0] == nil }, removed = a.keys.filter { b[$0] == nil }
            let changed = b.keys.filter { key in a[key].map { $0 != b[key]! } ?? false }
            guard !added.isEmpty || !removed.isEmpty || !changed.isEmpty else { continue }
            print("■ \(table): 추가 \(added.count) · 삭제 \(removed.count) · 변경 \(changed.count)")
            func show(_ rowKey: String, _ values: [String?]) -> String {
                zip(columns, values).map { column, value in
                    let v = sensitive(table, column, rowKey) ? "(가림)" : String((value ?? "nil").prefix(column == "Cues" ? 60 : 90))
                    return "\(column)=\(v)"
                }.joined(separator: " | ")
            }
            for rowKey in added.sorted().prefix(6) { print("  + \(rowKey): \(show(rowKey, b[rowKey]!))") }
            for rowKey in removed.sorted().prefix(6) { print("  - \(rowKey): \(show(rowKey, a[rowKey]!))") }
            for rowKey in changed.sorted().prefix(8) {
                let diffs = columns.indices.filter { a[rowKey]![$0] != b[rowKey]![$0] }.map { i -> String in
                    let column = columns[i]
                    if sensitive(table, column, rowKey) { return "\(column): (바뀜)" }
                    let old = String((a[rowKey]![i] ?? "nil").prefix(column == "Cues" ? 40 : 90))
                    let new = String((b[rowKey]![i] ?? "nil").prefix(column == "Cues" ? 40 : 90))
                    return "\(column): \(old) → \(new)"
                }
                print("  ~ \(rowKey): \(diffs.joined(separator: " ; "))")
            }
        }

    case "cue-json":
        // 한 곡의 contentCue JSON 원문(읽기 전용)
        guard args.count > 2 else { return }
        let db = try CipherDatabase(path: args[1], key: RekordboxKey.derive())
        try db.query("SELECT Cues, rb_cue_count, rb_data_status, rb_local_synced FROM contentCue WHERE ContentID = '\(args[2])'") { r in
            print("rb_cue_count \(r.int(1) ?? -1) · status \(r.int(2) ?? -1) · synced \(r.int(3) ?? -1)")
            print(r.string(0) ?? "")
        }
        try db.query("SELECT CueUpdated, rb_data_status, rb_local_synced, UUID FROM djmdContent WHERE ID = '\(args[2])'") { r in
            print("content CueUpdated \(r.string(0) ?? "nil") · status \(r.int(1) ?? -1) · synced \(r.int(2) ?? -1)")
        }

    case "cue-rows-probe":
        let db = try CipherDatabase(path: args[1], key: RekordboxKey.derive())
        try db.query("""
            SELECT count(*) FROM djmdContent t WHERE t.rb_local_deleted = 0
              AND NOT EXISTS (SELECT 1 FROM djmdCue c WHERE c.ContentID = t.ID)
            """) { print("큐 없는 곡:", $0.int(0) ?? 0) }
        try db.query("""
            SELECT count(*), sum(Cues = '[]'), sum(Cues IS NULL) FROM contentCue cc WHERE cc.rb_local_deleted = 0
              AND NOT EXISTS (SELECT 1 FROM djmdCue c WHERE c.ContentID = cc.ContentID)
            """) { print("큐 없는데 contentCue 있음:", $0.int(0) ?? 0, "빈 배열", $0.int(1) ?? 0, "NULL", $0.int(2) ?? 0) }
        try db.query("SELECT sum(ID = (SELECT UUID FROM djmdContent t WHERE t.ID = cc.ContentID)), count(*) FROM contentCue cc") { print("contentCue.ID = 곡 UUID:", $0.int(0) ?? 0, "/", $0.int(1) ?? 0) }
        try db.query("""
            SELECT ID, ContentID, rb_cue_count, UUID, rb_data_status, rb_local_data_status, rb_local_deleted, rb_local_synced, usn, rb_local_usn, created_at, updated_at
            FROM contentCue WHERE rb_data_status = 0 AND rb_local_synced = 0 ORDER BY created_at DESC LIMIT 2
            """) { r in print("로컬에서 만든 contentCue:", (Int32(0)..<12).map { r.string($0) ?? "nil" }.joined(separator: " | ")) }
        try db.query("SELECT Cues FROM contentCue WHERE Cues LIKE '%InPointSeekInfo%' LIMIT 1") { r in
            let text = r.string(0) ?? ""
            if let range = text.range(of: "InPointSeekInfo") {
                let lower = text.index(range.lowerBound, offsetBy: -160, limitedBy: text.startIndex) ?? text.startIndex
                let upper = text.index(range.upperBound, offsetBy: 200, limitedBy: text.endIndex) ?? text.endIndex
                print("SeekInfo 주변:", String(text[lower..<upper]))
            }
        }
        try db.query("SELECT rb_data_status, count(*) FROM djmdContent WHERE rb_local_deleted = 0 GROUP BY 1") { print("djmdContent status \($0.int(0) ?? -1): \($0.int(1) ?? 0)") }

    case "sql":
        // 스냅샷 사본에 읽기 전용 SELECT(개발용). 민감한 표(agentRegistry·자격 정보)는 막는다.
        guard args.count > 2 else { print("anicue sql <사본.db> <SELECT…>"); return }
        let sql = args[2]
        guard sql.lowercased().hasPrefix("select") || sql.lowercased().hasPrefix("pragma table_info"),
              !["agentregistry", "credential", "token", "cloudagent"].contains(where: sql.lowercased().contains)
        else { print("허용하지 않는 쿼리"); return }
        let db = try CipherDatabase(path: args[1], key: RekordboxKey.derive())
        try db.query(sql) { r in print((Int32(0)..<Int32(r.count)).map { r.string($0) ?? "nil" }.joined(separator: " | ")) }

    case "cue-write":
        // 큐 초안을 rekordbox DB에 직접 쓴다. 기본은 --db 사본. 라이브 DB는 --live를 줘야 하고 rekordbox가 꺼져 있어야 한다.
        let live = args.contains("--live")
        guard live || value(after: "--db", in: args) != nil else { print("anicue cue-write --db <사본.db> [--dry-run] [--uuid U] | --live"); return }
        let database = live ? RekordboxWriter.liveDatabase : URL(filePath: value(after: "--db", in: args)!)
        let uuids = value(after: "--uuid", in: args).map { $0.components(separatedBy: ",") } ?? CueDraftStore.uuids().sorted()
        let drafts = uuids.compactMap(CueDraftStore.load(trackUUID:))
        let backups = live ? RekordboxWriter.backupDirectory : database.deletingLastPathComponent().appending(path: "backups")
        let report = try RekordboxWriter.write(drafts: drafts, to: database, dryRun: args.contains("--dry-run"), backups: backups)
        for outcome in report.outcomes {
            let mark = switch outcome.status { case .written: "✓"; case .blocked: "✗"; case .unchanged: "·" }
            print("\(mark) \(outcome.title.prefix(34)) — 지움 \(outcome.removed) · 넣음 \(outcome.added)\(outcome.reason.map { " · \($0)" } ?? "")")
        }
        print("\(report.dryRun ? "미리 보기(되돌림)" : "씀") · 쓴 곡 \(report.written.count) · 막힌 곡 \(report.blocked.count) · 백업 \(report.backup ?? "없음")")

    case "rekordbox-restore":
        // 백업으로 되돌린다. 기본은 --db 사본. 라이브 DB는 --live(rekordbox가 꺼져 있어야 한다). 백업 목록은 인자 없이.
        let live = args.contains("--live")
        guard let folder = value(after: "--backup", in: args), live || value(after: "--db", in: args) != nil else {
            for backup in RekordboxWriter.backups() {
                print(backup.url.lastPathComponent, "·", backup.titles.prefix(5).joined(separator: ", "), "· 카운터", backup.report?.finalUpdateCount ?? -1)
            }
            print("anicue rekordbox-restore --backup <폴더> (--db <사본> | --live)")
            return
        }
        let database = live ? RekordboxWriter.liveDatabase : URL(filePath: value(after: "--db", in: args)!)
        let saved = try RekordboxWriter.restore(URL(filePath: folder), to: database,
                                                backups: live ? RekordboxWriter.backupDirectory : database.deletingLastPathComponent().appending(path: "backups"))
        print("되돌림 완료 · 되돌리기 전 상태 백업: \(saved.path)")

    case "cue-write-selftest":
        // 사본 DB에서 기존 큐 지우기·옮기기·핫큐 추가·막힘 조건을 시험한다(개발용, 사본만).
        guard let path = value(after: "--db", in: args), !RekordboxWriter.liveDatabase.path.hasSuffix(path) else { print("--db <사본>"); return }
        let database = URL(filePath: path)
        let library = try RekordboxLibrary.load(snapshot: database)
        let meta = try CipherDatabase(path: path, key: RekordboxKey.derive())
        var formats: [String: (Int, Int)] = [:]
        try meta.query("SELECT ID, FileType, BitRate FROM djmdContent") { formats[$0.string(0) ?? ""] = ($0.int(1) ?? 0, $0.int(2) ?? 0) }
        var seek: Set<String> = []
        try meta.query("SELECT DISTINCT ContentID FROM djmdCue WHERE InMpegFrame != 0 OR InPointSeekInfo IS NOT NULL") { seek.insert($0.string(0) ?? "") }
        var legacy: Set<String> = []
        try meta.query("SELECT ContentID FROM contentCue WHERE rb_cue_count IS NULL") { legacy.insert($0.string(0) ?? "") }
        meta.close()
        func editable(_ t: Track) -> Bool {
            guard let f = formats[t.id], !(seek.contains(t.id) && f.0 != 5), !t.isStreaming else { return false }
            return (f.0 == 1 && f.1 > 0) || f.0 == 4 || f.0 == 11 || (f.0 == 5 && args.contains("--flac"))
        }
        let candidates = library.tracks.filter { t in
            editable(t) && library.cues(for: t).filter { !$0.isAutoGenerated && !$0.isLoop && $0.activeLoop == 0 }.compactMap(EditableCue.init).count >= 3
        }
        let flacOnly = args.contains("--flac")
        let pool = flacOnly ? candidates.filter { formats[$0.id]?.0 == 5 } : candidates
        let newFormat = pool.filter { !legacy.contains($0.id) }.prefix(3)
        let oldFormat = pool.filter { legacy.contains($0.id) }.prefix(3)
        var drafts: [CueDraft] = []
        for (n, track) in (Array(newFormat) + Array(oldFormat)).enumerated() {
            var draft = CueDraft(trackUUID: track.uuid, rekordboxCues: library.cues(for: track))
            let memories = draft.cues.filter { $0.kind == .memory }
            if let first = memories.first { draft.remove(first.id) }                  // 지우기
            if memories.count > 1 { var moved = memories[1]; moved.time += 0.5; moved.name = "anicue 옮김"; draft.place(moved) }  // 옮기기+이름
            let free = (0..<8).first { slot in !draft.cues.contains { $0.kind == .hot(slot) } }
            if let free { draft.place(EditableCue(kind: .hot(free), time: 10 + Double(n), name: n == 0 ? "따옴표\"·역슬래시\\" : "")) }  // 핫큐 추가
            draft.place(EditableCue(kind: .memory, time: 20.123 + Double(n)))        // 메모리 추가
            drafts.append(draft)
            print("시험 곡 \(track.title.prefix(24)) · \(legacy.contains(track.id) ? "옛 JSON" : "새 JSON") · 변경 \(draft.changes.count)")
        }
        // 막혀야 하는 경우: 초안 뒤 rekordbox가 바뀐 곡, VBR MP3, FLAC
        if let track = candidates.dropFirst(6).first {
            var stale = CueDraft(trackUUID: track.uuid, rekordboxCues: library.cues(for: track))
            stale.base[0].time += 1   // rekordbox 쪽 큐가 달라진 것처럼
            stale.place(EditableCue(kind: .memory, time: 30))
            drafts.append(stale)
        }
        for (label, match) in [("VBR", { (f: (Int, Int)) in f.0 == 1 && f.1 == 0 }), ("FLAC", { (f: (Int, Int)) in f.0 == 5 })] {
            if let track = library.tracks.first(where: { formats[$0.id].map(match) ?? false }) {
                var d = CueDraft(trackUUID: track.uuid, rekordboxCues: library.cues(for: track))
                d.place(EditableCue(kind: .memory, time: 12))
                drafts.append(d)
                print("막혀야 함(\(label)): \(track.title.prefix(24))")
            }
        }
        let report = try RekordboxWriter.write(drafts: drafts, to: database, dryRun: false,
                                               backups: database.deletingLastPathComponent().appending(path: "backups"))
        for o in report.outcomes {
            print("\(o.status.rawValue) \(o.title.prefix(24)) — 지움 \(o.removed) · 넣음 \(o.added)\(o.reason.map { " · \($0)" } ?? "")")
        }
        // 다시 읽어 초안과 같은지
        let after = try RekordboxLibrary.load(snapshot: database)
        for draft in drafts {
            guard report.outcomes.contains(where: { $0.trackUUID == draft.trackUUID && $0.status == .written }),
                  let track = after.tracks.first(where: { $0.uuid == draft.trackUUID }) else { continue }
            let now = CueDraft(trackUUID: track.uuid, rekordboxCues: after.cues(for: track)).cues
            let same = RekordboxWriter.key(now, withSource: false) == RekordboxWriter.key(draft.cues, withSource: false)
            print("재확인 \(track.title.prefix(24)): \(same ? "초안과 같음" : "다름!")")
        }
        print("백업:", report.backup ?? "")

    case "loudness":
        // 파일의 BS.1770 통합 음량·피크·클리핑 흔적(개발용)
        for path in args.dropFirst() {
            let file = try AVAudioFile(forReading: URL(filePath: path))
            guard let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat, frameCapacity: AVAudioFrameCount(file.length)) else { continue }
            try file.read(into: buffer)
            let frames = Int(buffer.frameLength)
            let channels = (0..<Int(buffer.format.channelCount)).map { UnsafeBufferPointer(start: buffer.floatChannelData![$0], count: frames) }
            let started = Date()
            let l = Loudness.measure(channels: channels, sampleRate: buffer.format.sampleRate)
            print(String(format: "%.2f LUFS · 피크 %.2f dBFS · 클리핑 %d · %.0fms · %@", l.integrated ?? -999, l.peak, l.clippedRuns,
                         Date().timeIntervalSince(started) * 1000, (path as NSString).lastPathComponent))
        }

    case "vbr-dump":
        // VBR MP3 큐와 파일 구조를 JSON으로(규칙 맞추기용, 읽기 전용)
        let db = try CipherDatabase(path: value(after: "--db", in: args) ?? LibrarySnapshot.latest().path, key: RekordboxKey.derive())
        var byTrack: [String: (path: String, cues: [[Int]])] = [:]
        try db.query("""
            SELECT t.ID, t.FolderPath, c.InMsec, c.InMpegFrame, c.InMpegAbs, c.OutMsec, c.OutMpegFrame, c.OutMpegAbs FROM djmdCue c
            JOIN djmdContent t ON t.ID = c.ContentID WHERE t.FileType = 1 AND c.InMpegFrame != 0
            """) { r in
            byTrack[r.string(0) ?? "", default: (r.string(1) ?? "", [])].cues.append((2..<8).map { r.int(Int32($0)) ?? 0 })
        }
        var out: [[String: Any]] = []
        for (_, entry) in byTrack where FileManager.default.fileExists(atPath: entry.path) {
            guard let t = SeekInfo.mp3Frames(url: URL(filePath: entry.path)) else { continue }
            let size = (try? FileManager.default.attributesOfItem(atPath: entry.path)[.size] as? Int) ?? 0
            out.append(["name": (entry.path as NSString).lastPathComponent, "sr": t.sampleRate, "spf": t.samplesPerFrame,
                        "offsets": t.offsets.map { $0 - t.offsets[0] }, "first": t.offsets[0], "fileSize": size ?? 0,
                        "info": t.hasInfoFrame, "xingFrames": t.xingFrames ?? -1, "xingBytes": t.xingBytes ?? -1,
                        "toc": t.toc.map { $0.map(Int.init) } ?? [], "cues": entry.cues])
        }
        let data = try JSONSerialization.data(withJSONObject: out)
        try data.write(to: URL(filePath: value(after: "--out", in: args) ?? "/dev/stdout"))
        print("곡 \(out.count)")

    case "anlz-roundtrip":
        // 분석 파일을 읽고 다시 써서 바이트까지 같은지, 그리드 태그를 풀었다 다시 만들면 같은지(읽기 전용, 사본 폴더)
        guard args.count > 1 else { print("anicue anlz-roundtrip <USBANLZ 폴더>"); return }
        let root = URL(filePath: args[1])
        var files = 0, same = 0, tagSame = [0, 0], tagTotal = [0, 0], emptyPQT2 = 0, failures: [String] = []
        let walker = FileManager.default.enumerator(at: root, includingPropertiesForKeys: nil)
        var dats: [URL] = []
        while let url = walker?.nextObject() as? URL { if url.lastPathComponent == "ANLZ0000.DAT" { dats.append(url) } }
        for dat in dats {
            let ext = dat.deletingPathExtension().appendingPathExtension("EXT")
            for url in [dat, ext] where FileManager.default.fileExists(atPath: url.path) {
                files += 1
                guard let data = try? Data(contentsOf: url), let file = try? AnlzFile(data: data) else {
                    if failures.count < 5 { failures.append("못 읽음 \(url.path.suffix(50))") }
                    continue
                }
                if file.serialized() == data { same += 1 } else if failures.count < 5 { failures.append("다시 쓰기 다름 \(url.path.suffix(50))") }
            }
            guard let datFile = try? AnlzFile(url: dat), let z = datFile.tag("PQTZ") else { continue }
            let extFile = try? AnlzFile(url: ext)
            let q = extFile?.tag("PQT2")
            let decoded = BeatGridTags.decode(pqtz: z.bytes, pqt2: q?.bytes)
            tagTotal[0] += 1
            if BeatGridTags.pqtz(decoded.beats) == z.bytes { tagSame[0] += 1 } else if failures.count < 8 { failures.append("PQTZ 다름 \(dat.path.suffix(50))") }
            if let q {
                tagTotal[1] += 1
                let rebuilt = decoded.unknown == nil ? BeatGridTags.pqt2([], unknown: 0) : BeatGridTags.pqt2(decoded.beats, unknown: decoded.unknown ?? 0)
                if decoded.unknown == nil { emptyPQT2 += 1 }
                if rebuilt == q.bytes { tagSame[1] += 1 } else if failures.count < 8 { failures.append("PQT2 다름 \(ext.path.suffix(50))") }
            }
        }
        print("분석 파일 \(files)개 · 그대로 다시 쓰기 같음 \(same)")
        print("PQTZ 다시 만들기 같음 \(tagSame[0])/\(tagTotal[0]) · PQT2 같음 \(tagSame[1])/\(tagTotal[1]) (빈 PQT2 \(emptyPQT2))")
        failures.forEach { print("  ", $0) }

    case "key-eval":
        // 조표 흐름 추정의 주 조표를 rekordbox 키와 비교(읽기 전용). --penalty로 전환 벌점 조정
        let library = try RekordboxLibrary.load(snapshot: value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest())
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 40
        let penalties = (value(after: "--penalty", in: args) ?? "2").split(separator: ",").compactMap { Double($0) }
        var candidates = library.tracks.filter { !$0.isStreaming && KeyAnalyzer.signature(camelot: $0.key ?? "") != nil && FileManager.default.fileExists(atPath: $0.folderPath) }
        candidates.shuffle()
        var exact = [Int](repeating: 0, count: penalties.count), fifth = exact, modulated = exact, total = 0, examples: [String] = []
        // --train N: 앞 N곡으로 음 분포를 학습하고 나머지로 평가한다.
        let trainCount = Int(value(after: "--train", in: args) ?? "") ?? 0
        if trainCount > 0 {
            var majorSum = [Double](repeating: 0, count: 12), minorSum = majorSum, counts = [0, 0]
            for track in candidates.prefix(trainCount) {
                guard let rb = KeyAnalyzer.signature(camelot: track.key ?? ""),
                      let file = try? AVAudioFile(forReading: URL(filePath: track.folderPath)),
                      let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat, frameCapacity: AVAudioFrameCount(file.length)),
                      (try? file.read(into: buffer)) != nil, let data = buffer.floatChannelData else { continue }
                let frames = Int(buffer.frameLength)
                let channels = (0..<Int(buffer.format.channelCount)).map { UnsafeBufferPointer(start: data[$0], count: frames) }
                let chroma = KeyAnalyzer.chroma(channels: channels, sampleRate: buffer.format.sampleRate)
                let tonic = rb.minor ? (rb.signature + 9) % 12 : rb.signature
                let v = KeyAnalyzer.rotatedTotal(chroma: chroma, tonic: tonic)
                if rb.minor { for i in 0..<12 { minorSum[i] += v[i] }; counts[1] += 1 } else { for i in 0..<12 { majorSum[i] += v[i] }; counts[0] += 1 }
            }
            let learned = KeyAnalyzer.Profiles(major: majorSum.map { $0 / Double(max(counts[0], 1)) }, minor: minorSum.map { $0 / Double(max(counts[1], 1)) })
            KeyAnalyzer.profiles = learned
            print("학습: 장조 \(counts[0])곡 · 단조 \(counts[1])곡")
            print("  장조:", learned.major.map { String(format: "%.4f", $0) }.joined(separator: ", "))
            print("  단조:", learned.minor.map { String(format: "%.4f", $0) }.joined(separator: ", "))
            candidates.removeFirst(min(trainCount, candidates.count))
        }
        for track in candidates.prefix(limit) {
            guard let file = try? AVAudioFile(forReading: URL(filePath: track.folderPath)),
                  let buffer = AVAudioPCMBuffer(pcmFormat: file.processingFormat, frameCapacity: AVAudioFrameCount(file.length)),
                  (try? file.read(into: buffer)) != nil, let data = buffer.floatChannelData else { continue }
            let frames = Int(buffer.frameLength)
            let channels = (0..<Int(buffer.format.channelCount)).map { UnsafeBufferPointer(start: data[$0], count: frames) }
            let chroma = KeyAnalyzer.chroma(channels: channels, sampleRate: buffer.format.sampleRate)
            let grid = RekordboxShare.analysisURL(track.analysisDataPath).flatMap { try? BeatGrid.load(anlz: $0) }
            let windows = KeyAnalyzer.windows(grid: grid, duration: Double(frames) / buffer.format.sampleRate)
            guard let rb = KeyAnalyzer.signature(camelot: track.key ?? "") else { continue }
            total += 1
            for (i, penalty) in penalties.enumerated() {
                let result = KeyAnalyzer.segments(chroma: chroma, windows: windows, switchPenalty: penalty,
                                                  minWindows: Int(value(after: "--min", in: args) ?? "") ?? 12)
                guard let main = result.main else { continue }
                let diff = (KeyAnalyzer.camelotNumber(signature: main) - KeyAnalyzer.camelotNumber(signature: rb.signature) + 12) % 12
                if diff == 0 { exact[i] += 1 }
                if diff == 1 || diff == 11 { fifth[i] += 1 }
                if result.segments.count > 1 {
                    modulated[i] += 1
                    if i == 0, examples.count < 12 {
                        let flow = result.segments.map { String(format: "%@ %.0f~%.0f초", KeyAnalyzer.camelot(signature: $0.signature, minor: rb.minor), $0.start, $0.end) }
                        examples.append("\(track.title.prefix(24)) (rekordbox \(track.key ?? "")): " + flow.joined(separator: " → "))
                    }
                }
            }
        }
        for (i, penalty) in penalties.enumerated() {
            print(String(format: "벌점 %.1f · %d곡 · 주 조표 일치 %d (%.0f%%) · 5도 이웃 %d · 전조 있음 %d곡", penalty, total, exact[i],
                         Double(exact[i]) / Double(max(total, 1)) * 100, fifth[i], modulated[i]))
        }
        examples.forEach { print("  ", $0) }

    case "grid-repro":
        // rekordbox가 직접 고친 그리드를 우리 생성기로 바이트까지 재현하는지(읽기 전용)
        // anicue grid-repro <전 폴더> <후 폴더> <음원> <첫 박 초> <BPM> <첫 박 번호>
        guard args.count > 6, let bpm = Double(args[5]), let number = Int(args[6]) else { return }
        let before = URL(filePath: args[1]), after = URL(filePath: args[2]), audioURL = URL(filePath: args[3])
        // "auto": 편집 전 그리드의 정밀 첫 박(PQTZ + PQT2 소수)
        let beforeDat = try AnlzFile(url: before.appending(path: "ANLZ0000.DAT"))
        let beforeExt = try? AnlzFile(url: before.appending(path: "ANLZ0000.EXT"))
        let precise = BeatGridTags.decode(pqtz: beforeDat.tag("PQTZ")!.bytes, pqt2: beforeExt?.tag("PQT2")?.bytes).beats
        guard let start = args[4] == "auto" ? precise.first.map({ $0.time / 1000 }) : Double(args[4]) else { return }
        print("첫 박", start)
        let audio = try AVAudioFile(forReading: audioURL)
        let duration = Double(audio.length) / audio.processingFormat.sampleRate + RekordboxTimeline.predictedOffset(url: audioURL)
        let beats = RekordboxGridWriter.beats(segments: [GridSegment(start: start, bpm: bpm, firstBeatNumber: number)], duration: duration)
        var dat = try AnlzFile(url: before.appending(path: "ANLZ0000.DAT"))
        dat.replace("PQTZ", with: BeatGridTags.pqtz(beats))
        var ext = try AnlzFile(url: before.appending(path: "ANLZ0000.EXT"))
        if ext.tag("PQT2") != nil { ext.replace("PQT2", with: BeatGridTags.pqt2([], unknown: 0)) }
        let wantDat = try Data(contentsOf: after.appending(path: "ANLZ0000.DAT")), wantExt = try Data(contentsOf: after.appending(path: "ANLZ0000.EXT"))
        print(String(format: "곡 길이 %.3f초 · 박 %d개 · 앞 %@ · 끝 %.0f", duration, beats.count,
                     beats.prefix(4).map { String(Int($0.time)) }.joined(separator: ","), beats.last?.time ?? 0))
        print(".DAT 바이트까지 같음:", dat.serialized() == wantDat, "· .EXT 바이트까지 같음:", ext.serialized() == wantExt)

    case "make-grid-drafts":
        // 시험용: 분석된 곡 몇 개에 그리드 초안(이동·½박·1박 위치)을 만든다. ANICUE_HOME을 사본으로 줘야 한다.
        guard ProcessInfo.processInfo.environment["ANICUE_HOME"]?.isEmpty == false else { print("ANICUE_HOME을 사본 폴더로 주세요"); return }
        let library = try RekordboxLibrary.load(snapshot: value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest())
        var made = 0
        for track in library.tracks.shuffled() where !track.isStreaming && (track.bpm ?? 0) > 0 && made < 3 {
            guard let url = RekordboxShare.analysisURL(track.analysisDataPath),
                  FileManager.default.fileExists(atPath: url.deletingPathExtension().appendingPathExtension("EXT").path),
                  let grid = try? BeatGrid.load(anlz: url), grid.beats.count > 64, FileManager.default.fileExists(atPath: track.folderPath) else { continue }
            var draft = GridDraft(trackUUID: track.uuid, grid: grid)
            guard draft.base.count == 1 else { continue }
            switch made {
            case 0: draft.shift(by: 0.012)
            case 1: draft.shift(by: 30 / draft.segments[0].bpm)          // ½박
            default: draft.segments[0].firstBeatNumber = draft.segments[0].firstBeatNumber % 4 + 1   // 1박 위치
            }
            try GridDraftStore.save(draft)
            print("초안: \(track.title.prefix(30)) · \(["+12ms", "½박", "1박 위치"][made])")
            made += 1
        }

    case "grid-write-test":
        // 사본 DB·사본 분석 폴더에 BPM 변경 그리드를 써 본다. anicue grid-write-test <사본.db> <사본 share 뿌리> <UUID> <BPM>
        guard args.count > 4, let bpm = Double(args[4]) else { return }
        let db = URL(filePath: args[1]), root = URL(filePath: args[2]), uuid = args[3]
        let library = try RekordboxLibrary.load(snapshot: db)
        guard let track = library.tracks.first(where: { $0.uuid == uuid }),
              let path = track.analysisDataPath else { print("곡 없음"); return }
        let datURL = root.appending(path: String(path.drop(while: { $0 == "/" })))
        let grid = try BeatGrid.load(anlz: datURL)
        var draft = GridDraft(trackUUID: uuid, grid: grid)
        draft.setBPM(bpm, at: 0)
        let report = try RekordboxWriter.write(drafts: [], grids: [draft], to: db, dryRun: false,
                                               backups: db.deletingLastPathComponent().appending(path: "backups"), shareRoot: root)
        for o in report.gridOutcomes ?? [] { print(o.status.rawValue, o.title, o.reason ?? "", "박", o.added) }

    case "tempo-scan":
        // 라이브러리 전체 그리드에서 변속 곡을 찾는다(시간 측정용)
        let library = try RekordboxLibrary.load(snapshot: value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest())
        let started = Date()
        var found: [(String, [Double])] = [], read = 0
        for track in library.tracks where !track.isStreaming {
            guard let url = RekordboxShare.analysisURL(track.analysisDataPath), let grid = try? BeatGrid.load(anlz: url) else { continue }
            read += 1
            let changes = grid.tempoChanges
            if !changes.isEmpty { found.append((track.title, changes)) }
        }
        print(String(format: "그리드 %d곡 읽음 · 변속 곡 %d곡 · %.2f초", read, found.count, Date().timeIntervalSince(started)))
        for (title, bpms) in found.prefix(12) { print("  \(title.prefix(30)): " + bpms.map { String(format: "%.0f", $0) }.joined(separator: "→")) }

    case "tempo-estimate-check":
        // rekordbox가 변속으로 잡은 곡에서 anicue 추정도 구간을 나누는지(읽기 전용, MU 분석은 캐시 사용)
        let library = try RekordboxLibrary.load(snapshot: value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest())
        var checked = 0, split = 0
        for track in library.tracks where !track.isStreaming && FileManager.default.fileExists(atPath: track.folderPath) {
            guard let anlz = RekordboxShare.analysisURL(track.analysisDataPath), let grid = try? BeatGrid.load(anlz: anlz) else { continue }
            let rb = grid.tempoChanges
            guard !rb.isEmpty else { continue }
            let url = URL(filePath: track.folderPath)
            guard let analysis = try? await PartAnalyzer.analyze(fileAt: url, cacheKey: track.uuid),
                  let onset = try? OnsetEnvelope.compute(url: url),
                  let estimate = GridEstimator.estimate(beats: analysis.beats, bars: analysis.bars, duration: analysis.duration, onset: onset)
            else { continue }
            checked += 1
            let ours = estimate.segments.map { String(format: "%.0f", $0.bpm) }.joined(separator: "→")
            if estimate.segments.count > 1 { split += 1 }
            print("\(track.title.prefix(26)) · rekordbox \(rb.map { String(format: "%.0f", $0) }.joined(separator: "→")) · anicue \(ours)")
        }
        print("변속 곡 \(checked)곡 중 anicue도 구간을 나눈 곡 \(split)")

    case "gain-write-test":
        // 사본 DB에 오토게인을 써 본다. anicue gain-write-test <사본.db> <UUID> <선형 게인>
        guard args.count > 3, let linear = Double(args[3]) else { return }
        let db = URL(filePath: args[1])
        let report = try RekordboxWriter.write(drafts: [], gains: [args[2]: 20 * log10(Double(Float(linear)))], to: db, dryRun: false,
                                               backups: db.deletingLastPathComponent().appending(path: "backups"))
        for o in report.gainOutcomes ?? [] { print(o.status.rawValue, o.title, o.reason ?? "", o.added) }

    case "seekinfo-check":
        // rekordbox가 적은 FLAC SeekInfo·VBR MP3 MPEG 위치를 우리 계산과 전수 대조(읽기 전용)
        let db = try CipherDatabase(path: value(after: "--db", in: args) ?? LibrarySnapshot.latest().path, key: RekordboxKey.derive())
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 100_000
        var flac: [String: (path: String, cues: [(Int, String, String?, Int?)])] = [:]
        try db.query("""
            SELECT t.ID, t.FolderPath, c.InMsec, c.InPointSeekInfo, c.OutPointSeekInfo, c.OutMsec FROM djmdCue c JOIN djmdContent t ON t.ID = c.ContentID
            WHERE t.FileType = 5 AND c.InPointSeekInfo IS NOT NULL
            """) { r in
            let id = r.string(0) ?? ""
            flac[id, default: (r.string(1) ?? "", [])].cues.append((r.int(2) ?? 0, r.string(3) ?? "", r.string(4), r.int(5)))
        }
        var same = [0, 0], differ = 0, outSame = 0, outDiffer = 0, missing = 0, samples: [String] = []
        for (_, entry) in flac.prefix(limit) {
            guard FileManager.default.fileExists(atPath: entry.path), let table = SeekInfo.flacFrames(url: URL(filePath: entry.path)) else { missing += 1; continue }
            for (msec, stored, outStored, outMsec) in entry.cues {
                let floorSample = msec * table.sampleRate / 1000
                let roundSample = Int((Double(msec) * Double(table.sampleRate) / 1000).rounded())
                let a = SeekInfo.flacSeekInfo(frames: table.frames, sample: floorSample)
                let b = SeekInfo.flacSeekInfo(frames: table.frames, sample: roundSample)
                if a == stored { same[0] += 1 }
                if b == stored { same[1] += 1 }
                if a != stored && b != stored {
                    differ += 1
                    if samples.count < 6 { samples.append("\((entry.path as NSString).lastPathComponent.prefix(30)) \(msec)ms: rekordbox \(stored) · 우리 \(a ?? "nil")") }
                }
                if let outMsec, outMsec > 0, let outStored {
                    let o = SeekInfo.flacSeekInfo(frames: table.frames, sample: outMsec * table.sampleRate / 1000)
                    if o == outStored { outSame += 1 } else { outDiffer += 1 }
                }
            }
        }
        print("FLAC \(flac.count)곡 · 큐 일치(내림) \(same[0]) · 일치(반올림) \(same[1]) · 둘 다 다름 \(differ) · 파일 없음·못 읽음 \(missing)곡 · 루프 끝 일치 \(outSame)/\(outSame + outDiffer)")
        samples.forEach { print("  ", $0) }

        var vbr: [String: (path: String, cues: [(Int, Int, Int, Int)])] = [:]
        try db.query("""
            SELECT t.ID, t.FolderPath, c.InMsec, c.InFrame, c.InMpegFrame, c.InMpegAbs FROM djmdCue c JOIN djmdContent t ON t.ID = c.ContentID
            WHERE t.FileType = 1 AND c.InMpegFrame != 0
            """) { r in
            let id = r.string(0) ?? ""
            vbr[id, default: (r.string(1) ?? "", [])].cues.append((r.int(2) ?? 0, r.int(3) ?? 0, r.int(4) ?? 0, r.int(5) ?? 0))
        }
        var frameRule = 0, total = 0, notFrame = 0, lagCounts: [Int: Int] = [:], vbrMissing = 0, vbrSamples: [String] = [], detailCount = 0
        for (_, entry) in vbr.prefix(limit) {
            guard FileManager.default.fileExists(atPath: entry.path), let table = SeekInfo.mp3Frames(url: URL(filePath: entry.path)) else { vbrMissing += 1; continue }
            // 기준점 후보: 첫 프레임(Xing 포함) · Xing 다음 프레임
            let bases = [table.offsets[0], table.offsets.count > 1 ? table.offsets[1] : table.offsets[0]]
            var hits = [0, 0]
            for (i, base) in bases.enumerated() {
                let set = Set(table.offsets.map { $0 - base })
                hits[i] = entry.cues.filter { set.contains($0.3) }.count
            }
            let base = hits[1] > hits[0] ? bases[1] : bases[0]
            let index = Dictionary(table.offsets.enumerated().map { ($1 - base, $0) }, uniquingKeysWith: { a, _ in a })
            if vbrSamples.count < 3 { vbrSamples.append("기준 맞춤: 첫 프레임 \(hits[0])/\(entry.cues.count) · Xing 다음 \(hits[1])/\(entry.cues.count) · Info 프레임 \(table.hasInfoFrame)") }
            for (msec, inFrame, mpegFrame, abs) in entry.cues {
                total += 1
                if mpegFrame == inFrame / 2 { frameRule += 1 }
                guard let k = index[abs] else {
                    notFrame += 1
                    if vbrSamples.count < 4 { vbrSamples.append("\((entry.path as NSString).lastPathComponent.prefix(30)) \(msec)ms abs \(abs) 프레임 경계 아님 · 첫 프레임 \(table.offsets.first ?? -1)") }
                    continue
                }
                // 시간으로 센 프레임 번호와의 차이
                let byTime = Int(Double(msec) / 1000 * Double(table.sampleRate) / Double(table.samplesPerFrame))
                lagCounts[k - byTime, default: 0] += 1
                if args.contains("--detail"), detailCount < 40 {
                    detailCount += 1
                    let exact = Double(msec) / 1000 * Double(table.sampleRate) / Double(table.samplesPerFrame)
                    let target = min(Int(exact), table.offsets.count - 1)
                    let bytes = table.offsets[target] - table.offsets[k]
                    let avg = target > k ? bytes / (target - k) : 0
                    print(String(format: "  %@ %7dms · 프레임 %5d · 시간 %9.3f · 차 %6.3f · 바이트 거리 %6d · 평균 프레임 %4d · sr %d",
                                 String((entry.path as NSString).lastPathComponent.prefix(18)), msec, k, exact, Double(k) - exact, bytes, avg,
                                 table.sampleRate))
                }
            }
        }
        print("VBR MP3 \(vbr.count)곡 · 큐 \(total) · InMpegFrame = InFrame/2 \(frameRule) · InMpegAbs가 프레임 경계 아님 \(notFrame) · 파일 없음·못 읽음 \(vbrMissing)곡")
        print("  (InMpegAbs 프레임 번호 − 시간으로 센 번호) 분포:", lagCounts.sorted { $0.value > $1.value }.prefix(8).map { "\($0.key):\($0.value)" }.joined(separator: " "))
        vbrSamples.forEach { print("  ", $0) }

    case "cue-json-roundtrip":
        // 라이브러리의 모든 contentCue JSON을 읽고 다시 써서 원문과 같은지(읽기 전용)
        let db = try CipherDatabase(path: args.count > 1 ? args[1] : LibrarySnapshot.latest().path, key: RekordboxKey.derive())
        var same = 0, differ = 0, failed = 0
        try db.query("SELECT ContentID, Cues FROM contentCue WHERE rb_local_deleted = 0") { r in
            guard let text = r.string(1) else { return }
            guard let objects = try? CueJSON.parse(text) else { failed += 1; return }
            let again = CueJSON.serialize(objects)
            if again == text { same += 1 } else {
                differ += 1
                if differ <= 2 {
                    let a = Array(text), b = Array(again)
                    let i = (0..<min(a.count, b.count)).first { a[$0] != b[$0] } ?? min(a.count, b.count)
                    print("다름 \(r.string(0) ?? ""): 원문 …\(String(a[max(0, i - 60)..<min(a.count, i + 60)]))…\n       다시 …\(String(b[max(0, i - 60)..<min(b.count, i + 60)]))…")
                }
            }
        }
        print("원문과 같음 \(same) · 다름 \(differ) · 못 읽음 \(failed)")

    case "path":
        // 제목으로 파일 경로 찾기(개발용)
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        guard args.count > 1 else { return }
        for track in library.tracks where track.title.contains(args[1]) && !track.isStreaming { print(track.folderPath) }

    case "tempo-debug":
        // 한 곡의 BPM 후보별 어택 점수(위상 ±25ms 최적화 포함)와 히스토그램 봉우리를 본다.
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        guard args.count > 1, let track = library.tracks.first(where: { $0.title.contains(args[1]) }) else { print("곡 없음"); return }
        let url = URL(filePath: track.folderPath)
        let onset = try OnsetEnvelope.compute(url: url)
        let analysis = try await PartAnalyzer.analyze(fileAt: url, cacheKey: track.uuid)
        let offset = RekordboxTimeline.predictedOffset(url: url)
        print("rb BPM \(track.bpm ?? 0) · MU BPM \(analysis.bpm ?? 0) · 시간축 차이 \(offset * 1000)ms")
        if let dat = RekordboxShare.analysisURL(track.analysisDataPath), let grid = try? BeatGrid.load(anlz: dat), let first = grid.beats.first {
            let rbTimes = grid.beats.map { $0.time - offset }
            let rbScore = rbTimes.reduce(0.0) { $0 + Double(onset.value(at: $1)) } / Double(rbTimes.count)
            print(String(format: "rekordbox 그리드 박 평균 어택 %.4f (첫 박 %.3f)", rbScore, first.time))
        }
        let center = track.bpm ?? analysis.bpm ?? 120
        let start = analysis.beats.first ?? 0
        for step in -12...12 {
            let bpm = (center * 100).rounded() / 100 + Double(step) * 0.02
            let period = 60 / bpm
            var best = 0.0
            // 위상은 MU 첫 박 근처 한 주기 안을 1ms 간격으로
            for phaseStep in 0..<Int(period * 1000) {
                let phase = start + Double(phaseStep) / 1000
                var sum = 0.0, n = 0
                var t = phase.truncatingRemainder(dividingBy: period)
                while t < onset.duration - 1 { sum += Double(onset.value(at: t)); n += 1; t += period }
                best = max(best, sum / Double(max(n, 1)))
            }
            print(String(format: "  %.2f BPM · 최고 평균 어택 %.4f", bpm, best))
        }

    case "timeline-debug":
        // 한 곡의 rekordbox 파형 길이·상관 곡선을 본다.
        let snapshot = try LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        guard args.count > 1, let track = library.tracks.first(where: { $0.title.contains(args[1]) }),
              let dat = RekordboxShare.analysisURL(track.analysisDataPath) else { print("곡 없음"); return }
        let heights = try RekordboxTimeline.detailWaveform(ext: RekordboxTimeline.extURL(forAnalysis: dat))
        let file = try AVAudioFile(forReading: URL(filePath: track.folderPath))
        let duration = Double(file.length) / file.processingFormat.sampleRate
        print("rb 칸 \(heights.count) · 길이×150 \(Int(duration * 150)) · 길이 \(duration)")
        print("rb 앞 60칸:", heights.prefix(60).map(String.init).joined(separator: " "))
        let peaks = try RekordboxTimeline.millisecondPeaks(url: URL(filePath: track.folderPath))
        let ours = RekordboxTimeline.binned(peaks, lagMs: 0, bins: 60).map { String(format: "%.0f", $0 * 31) }
        print("우리 앞 60칸:", ours.joined(separator: " "))
        for lag in stride(from: -400, through: 400, by: 20) {
            let c = RekordboxTimeline.correlation(heights.map(Double.init), RekordboxTimeline.binned(peaks, lagMs: Double(lag), bins: heights.count))
            print(String(format: "  lag %+4dms · %.3f", lag, c))
        }

    case "bpm-histogram":
        let library = try RekordboxLibrary.load(snapshot: LibrarySnapshot.latest())
        let bpms = library.tracks.compactMap(\.bpm).filter { $0 > 0 }
        var bins: [Int: Int] = [:]
        for bpm in bpms { bins[Int(bpm / 5) * 5, default: 0] += 1 }
        for (start, count) in bins.sorted(by: { $0.key < $1.key }) {
            print(String(format: "%3d~%3d %5d %@", start, start + 4, count, String(repeating: "█", count: max(1, count / 20))))
        }

    case "timeline-check":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 40
        try timelineCheck(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "eval-cues":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 30
        try await evaluateCues(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "parse":
        guard args.count > 1 else { print(usage); return }
        let comment = args[1]
        print("분류: \(CommentClassifier.classify(comment).rawValue)")
        if let parsed = ConventionParser.parse(comment) {
            dump(parsed)
        }

    default:
        print(usage)
    }
}

do {
    try await run()
} catch {
    FileHandle.standardError.write(Data("오류: \(error)\n".utf8))
    exit(1)
}
