import AnicueCore
import Foundation

let usage = """
    anicue — rekordbox 애니송 라이브러리 관리 도구 (읽기 전용 단계)

    사용법:
      anicue snapshot [--force]           rekordbox master.db 스냅샷 생성
      anicue report [--db PATH] [--files] 라이브러리 현황 (기본: 최신 스냅샷)
      anicue parse "<코멘트>"              코멘트 문법 파싱 결과 출력
      anicue analyze <파일|ContentID> [--db PATH]
                                          Music Understanding 파트 분석 (ContentID면 기존 큐와 비교)
      anicue mockup-data <ContentID> --out PATH [--db PATH]
                                          디자인 시안용 실데이터(JSON) 내보내기
      anicue grid-check [--limit N] [--db PATH]
                                          템포 구간으로 재생성한 그리드와 rekordbox 원본(PQTZ) 오차 측정
      anicue eval-cues [--limit N] [--db PATH]
                                          섹션 경계 메모리 큐 후보를 직접 찍은 큐와 비교 평가
    """

func clock(_ seconds: Double) -> String {
    String(format: "%d:%05.2f", Int(seconds) / 60, seconds.truncatingRemainder(dividingBy: 60))
}

func analyze(_ target: String, snapshotPath: String?) async throws {
    var url = URL(filePath: target)
    var track: Track?
    var cues: [Cue] = []
    if !FileManager.default.fileExists(atPath: target) {
        let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        guard let found = library.tracks.first(where: { $0.id == target }) else {
            print("트랙을 찾지 못했습니다: \(target)"); return
        }
        track = found
        cues = library.cues(for: found)
        url = URL(filePath: found.folderPath)
    }

    let started = Date()
    let analysis = try await PartAnalyzer.analyze(fileAt: url, cacheKey: track?.uuid)

    if let track { print("\(track.title) — \(track.artist ?? "")\n코멘트: \(track.comment)") }
    print(String(format: "길이 %@ · BPM %@ · 분석 %.1f초 · 통합 음량 %@ LUFS",
                 clock(analysis.duration),
                 analysis.bpm.map { String(format: "%.1f", $0) } ?? "-",
                 Date().timeIntervalSince(started),
                 analysis.integratedLoudness.map { String(format: "%.1f", $0) } ?? "-"))
    print("키: " + analysis.keys.map { "\(clock($0.span.start)) \($0.name)" }.joined(separator: " → "))
    print("마디 \(analysis.bars.count) · 섹션 \(analysis.sections.count) · 세그먼트 \(analysis.segments.count) · 프레이즈 \(analysis.phrases.count)\n")

    print("섹션별 에너지 (음량 LUFS / 보컬 / 드럼 / 점수)")
    for e in PartLabeler.energies(analysis) {
        print(String(format: "  %@–%@  %6.1f  %.2f  %.2f  %.2f",
                     clock(e.span.start), clock(e.span.end), e.loudness, e.vocal, e.drum, e.score))
    }

    print("\n파트 추정 v0")
    for m in PartLabeler.label(analysis) {
        print("  \(m.label.rawValue)\t\(clock(m.time))\t\(m.bar.map { "\($0)마디" } ?? "")\t신뢰도 \(m.confidence)")
    }

    if !cues.isEmpty {
        print("\nrekordbox 기존 큐 (직접 찍은 것)")
        for cue in cues.filter({ !$0.isAutoGenerated }).sorted(by: { $0.inMsec < $1.inMsec }) {
            let time = Double(cue.inMsec) / 1000
            let slot = cue.hotCueSlot.map { "핫큐 \($0)" } ?? "메모리"
            print("  \(slot)\t\(clock(time))\t\(analysis.barNumber(at: time).map { "\($0)마디" } ?? "")")
        }
    }
}

/// 직접 찍은 큐(자동 이름 제외)가 3개 이상인 로컬 곡을 UUID 순으로 뽑아 평가한다.
func evaluateCues(limit: Int, snapshotPath: String?) async throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    let sample = library.tracks
        .filter { !$0.isStreaming && FileManager.default.fileExists(atPath: $0.folderPath) }
        .filter { library.cues(for: $0).filter { !$0.isAutoGenerated }.count >= 3 }
        .sorted { $0.uuid < $1.uuid }
        .prefix(limit)

    var byBeat = CueEvaluation(), byQuarterSecond = CueEvaluation()
    var failures = 0
    var seconds: [Double] = []
    for (index, track) in sample.enumerated() {
        let started = Date()
        do {
            let analysis = try await PartAnalyzer.analyze(fileAt: URL(filePath: track.folderPath), cacheKey: track.uuid)
            seconds.append(Date().timeIntervalSince(started))
            // 같은 위치의 메모리 큐와 핫큐는 하나로 센다.
            var truth: [Double] = []
            for time in library.cues(for: track).filter({ !$0.isAutoGenerated }).map({ Double($0.inMsec) / 1000 }).sorted()
            where !truth.contains(where: { abs($0 - time) < 0.1 }) {
                truth.append(time)
            }
            let predicted = MemoryCueSuggester.candidates(analysis)
            let beat = analysis.bpm.map { 60 / $0 } ?? 0.4
            let e1 = CueEvaluation(truth: truth, predicted: predicted, tolerance: beat)
            let e2 = CueEvaluation(truth: truth, predicted: predicted, tolerance: 0.25)
            byBeat = byBeat + e1
            byQuarterSecond = byQuarterSecond + e2
            print(String(format: "%3d  재현 %2d/%-2d  정밀 %2d/%-2d  %4.1fs  %@",
                         index + 1, e1.truthMatched, e1.truth, e1.predictedMatched, e1.predicted,
                         seconds.last!, String(track.comment.prefix(40))))
        } catch {
            failures += 1
            print(String(format: "%3d  실패: %@", index + 1, String(describing: error)))
        }
    }

    let average = seconds.isEmpty ? 0 : seconds.reduce(0, +) / Double(seconds.count)
    print(String(format: "\n곡 %d (실패 %d) · 곡당 분석 평균 %.1f초", sample.count, failures, average))
    print(String(format: "±1박:    재현율 %.1f%% (%d/%d) · 정밀도 %.1f%% (%d/%d)",
                 byBeat.recall * 100, byBeat.truthMatched, byBeat.truth,
                 byBeat.precision * 100, byBeat.predictedMatched, byBeat.predicted))
    print(String(format: "±0.25초: 재현율 %.1f%% · 정밀도 %.1f%%",
                 byQuarterSecond.recall * 100, byQuarterSecond.precision * 100))
}

/// 디자인 시안에 넣을 실제 데이터. 앨범 커버 이미지는 넣지 않는다.
func exportMockupData(_ id: String, to out: URL, snapshotPath: String?) async throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    guard let track = library.tracks.first(where: { $0.id == id }) else { print("트랙 없음: \(id)"); return }
    let url = URL(filePath: track.folderPath)
    let analysis = try await PartAnalyzer.analyze(fileAt: url, cacheKey: track.uuid)
    let waveform = try WaveformAnalyzer.analyze(fileAt: url)
    let cues = library.cues(for: track).sorted { $0.inMsec < $1.inMsec }
    let hotA = cues.first { $0.hotCueSlot == "A" }.map { Double($0.inMsec) / 1000 } ?? 60
    let zoomStart = max(0, hotA - 12), zoomEnd = zoomStart + 24

    func row(_ t: Track) -> [String: Any] {
        let manual = library.cues(for: t).filter { !$0.isAutoGenerated }.count
        // 목록용 미니 개요 파형(160칸)과 큐 위치
        var mini: [String: Any] = [:]
        if !t.isStreaming, let w = try? WaveformAnalyzer.analyze(fileAt: URL(filePath: t.folderPath)).downsampled(to: 160) {
            mini = ["low": w.low, "mid": w.mid, "high": w.high, "duration": w.duration]
        }
        let cuePoints = library.cues(for: t).filter { !$0.isAutoGenerated }.map {
            ["time": Double($0.inMsec) / 1000, "slot": $0.hotCueSlot.map(String.init) ?? ""] as [String: Any]
        }
        return ["mini": mini, "cuePoints": cuePoints, "title": t.title, "artist": t.artist ?? "", "album": t.album ?? "", "comment": t.comment,
                "class": CommentClassifier.classify(t.comment).rawValue, "imported": t.importedOn ?? "",
                "plays": library.playCounts[t.id, default: 0], "bpm": t.bpm ?? 0, "key": t.key ?? "",
                "cues": library.cues(for: t).isEmpty ? "none" : (manual > 0 ? "manual \(manual)" : "auto"),
                "length": t.lengthSeconds]
    }
    // 목록: 선택 곡 + 규칙 코멘트 곡 + 2025~26 빈 코멘트 로컬 파일
    let local = library.tracks.filter { !$0.isStreaming }
    let convention = local.filter { CommentClassifier.classify($0.comment) == .convention && library.playCounts[$0.id, default: 0] > 3 }
        .sorted { $0.uuid < $1.uuid }.prefix(8)
    let backlog = local.filter { $0.comment.isEmpty && ["2025", "2026"].contains($0.importYear ?? "") }
        .sorted { $0.uuid < $1.uuid }.prefix(8)
    let parsed = ConventionParser.parse(track.comment)

    let energies = PartLabeler.energies(analysis)
    let lo = energies.map(\.score).filter(\.isFinite).min() ?? 0, hi = energies.map(\.score).filter(\.isFinite).max() ?? 1
    let overview = waveform.downsampled(to: 900)
    let zoom = waveform.slice(from: zoomStart, to: zoomEnd)
    let payload: [String: Any] = [
        "track": row(track).merging([
            "parsed": [
                "prefix": parsed?.prefix.rawValue ?? "", "work": parsed?.workName ?? "",
                "usage": parsed?.usages.map { $0.kind.rawValue + ($0.numbers.isEmpty ? "" : " " + $0.numbers.map(String.init).joined(separator: ",")) } ?? [],
            ],
            "duration": analysis.duration,
        ]) { a, _ in a },
        "library": [row(track)] + convention.map(row) + backlog.map(row),
        "counts": ["live": library.tracks.count, "backlog": backlog.count],
        "analysis": [
            "bpm": analysis.bpm ?? 0, "bars": analysis.bars.count,
            "key": analysis.keys.first?.name ?? "",
            "sections": energies.map { ["start": $0.span.start, "end": $0.span.end,
                                        "energy": hi > lo && $0.score.isFinite ? ($0.score - lo) / (hi - lo) : 0,
                                        "vocal": $0.vocal] },
            "barTimes": analysis.bars,
            "labels": PartLabeler.label(analysis).map { ["label": $0.label.rawValue, "time": $0.time] },
            "suggestions": MemoryCueSuggester.suggestions(analysis, existing: cues.map { Double($0.inMsec) / 1000 }),
        ],
        "cues": cues.map { ["slot": $0.hotCueSlot.map(String.init) ?? "", "time": Double($0.inMsec) / 1000,
                            "memory": $0.isMemoryCue, "auto": $0.isAutoGenerated] },
        "waveform": [
            "overview": ["rate": overview.rate, "low": overview.low, "mid": overview.mid, "high": overview.high],
            "zoom": ["start": zoomStart, "rate": zoom.rate, "low": zoom.low, "mid": zoom.mid, "high": zoom.high],
        ],
    ]
    let data = try JSONSerialization.data(withJSONObject: payload, options: [.sortedKeys])
    try data.write(to: out)
    print("\(out.path) (\(data.count / 1024)KB) · 파형 \(waveform.count)칸 · 확대 \(Int(zoomStart))~\(Int(zoomEnd))초")
}

func gridCheck(limit: Int, snapshotPath: String?) throws {
    let snapshot = try snapshotPath.map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
    let library = try RekordboxLibrary.load(snapshot: snapshot)
    var errors: [Double] = [], segmentCounts: [Int: Int] = [:], checked = 0, mismatchedCount = 0
    for track in library.tracks.sorted(by: { $0.uuid < $1.uuid }).prefix(limit) {
        guard let url = RekordboxShare.analysisURL(track.analysisDataPath),
              let grid = try? BeatGrid.load(anlz: url), !grid.beats.isEmpty else { continue }
        let draft = GridDraft(trackUUID: track.uuid, grid: grid)
        let duration = Double(track.lengthSeconds) + 1
        let rebuilt = draft.grid(duration: max(duration, grid.beats.last!.time + 0.01))
        segmentCounts[draft.segments.count, default: 0] += 1
        checked += 1
        // 원본 박마다 가장 가까운 재생성 박과의 차이
        var worst = 0.0
        for beat in grid.beats {
            let nearest = rebuilt.snap(beat.time)
            worst = max(worst, abs(nearest - beat.time))
        }
        if rebuilt.beats.count != grid.beats.count { mismatchedCount += 1 }
        errors.append(worst * 1000)
        if worst > 0.01 { print("  큰 오차 \(Int(worst * 1000))ms · 구간 \(draft.segments.count) · \(track.title.prefix(30))") }
    }
    errors.sort()
    func pct(_ p: Double) -> Double { errors.isEmpty ? 0 : errors[min(errors.count - 1, Int(Double(errors.count - 1) * p))] }
    print("검사 \(checked)곡 · 구간 수 분포 \(segmentCounts.sorted { $0.key < $1.key })")
    print(String(format: "곡별 최대 오차(ms): 중앙값 %.2f · 95%% %.2f · 99%% %.2f · 최대 %.2f", pct(0.5), pct(0.95), pct(0.99), errors.last ?? 0))
    print("오차 ≤1ms 곡: \(errors.filter { $0 <= 1.0005 }.count) · ≤2ms: \(errors.filter { $0 <= 2.0005 }.count) · 박 개수 불일치 곡: \(mismatchedCount)")
}

func value(after flag: String, in args: [String]) -> String? {
    guard let i = args.firstIndex(of: flag), i + 1 < args.count else { return nil }
    return args[i + 1]
}

func run() async throws {
    let args = Array(CommandLine.arguments.dropFirst())
    switch args.first {
    case "snapshot":
        let url = try LibrarySnapshot.take(force: args.contains("--force"))
        print(url.path)

    case "report":
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        print("스냅샷: \(snapshot.path)\n")
        print(LibraryReport(library: library, checkFiles: args.contains("--files")).render())

    case "analyze":
        guard args.count > 1 else { print(usage); return }
        try await analyze(args[1], snapshotPath: value(after: "--db", in: args))

    case "mockup-data":
        guard args.count > 1, let out = value(after: "--out", in: args) else { print(usage); return }
        try await exportMockupData(args[1], to: URL(filePath: out), snapshotPath: value(after: "--db", in: args))

    case "bench-load":
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let clock = ContinuousClock()
        var library: RekordboxLibrary!
        let tLoad = try clock.measure { library = try RekordboxLibrary.load(snapshot: snapshot) }
        var classified = 0
        let tClassify = clock.measure { for t in library.tracks { if CommentClassifier.classify(t.comment) == .convention { classified += 1 } } }
        let tParse = clock.measure { for t in library.tracks { _ = ConventionParser.parse(t.comment) } }
        let tReport = clock.measure { _ = LibraryReport(library: library) }
        let tTree = clock.measure { _ = PlaylistNode.tree(library.playlists) }
        print("DB 읽기 \(tLoad) · 분류 \(tClassify) · 파싱 \(tParse) · 현황 집계 \(tReport) · 플레이리스트 트리 \(tTree) · 곡 \(library.tracks.count)")

    case "bench-waveform":
        guard args.count > 1 else { return }
        let clock = ContinuousClock()
        var w: Waveform!
        let t = try clock.measure { w = try WaveformAnalyzer.analyze(fileAt: URL(filePath: args[1])) }
        print("파형 \(t) · \(w.count)칸 · \(Int(w.duration))초")
        if let out = value(after: "--out", in: args) { try JSONEncoder().encode(w).write(to: URL(filePath: out)) }

    case "parity-check":
        // 정규식 파서(이전)와 새 파서를 실제 라이브러리 전체 코멘트로 비교한다.
        let snapshot = try value(after: "--db", in: args).map { URL(filePath: $0) } ?? LibrarySnapshot.latest()
        let library = try RekordboxLibrary.load(snapshot: snapshot)
        var parseDiff = 0, classDiff = 0, checked = 0
        for comment in Set(library.allTracks.map(\.comment)) {
            checked += 1
            let old = RegexConventionParser.parse(comment), new = ConventionParser.parse(comment)
            if old != new {
                parseDiff += 1
                if parseDiff <= 12 { print("파싱 차이: \(comment)\n  이전 \(String(describing: old))\n  새것 \(String(describing: new))") }
            }
            let oldClass = RegexCommentClassifier.classify(comment), newClass = CommentClassifier.classify(comment)
            if oldClass != newClass {
                classDiff += 1
                if classDiff <= 12 { print("분류 차이: \(comment) · 이전 \(oldClass) · 새것 \(newClass)") }
            }
        }
        print("고유 코멘트 \(checked)개 · 파싱 차이 \(parseDiff) · 분류 차이 \(classDiff)")

    case "grid-check":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 500
        try gridCheck(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "eval-cues":
        let limit = Int(value(after: "--limit", in: args) ?? "") ?? 30
        try await evaluateCues(limit: limit, snapshotPath: value(after: "--db", in: args))

    case "parse":
        guard args.count > 1 else { print(usage); return }
        let comment = args[1]
        print("분류: \(CommentClassifier.classify(comment).rawValue)")
        if let parsed = ConventionParser.parse(comment) {
            dump(parsed)
        }

    default:
        print(usage)
    }
}

do {
    try await run()
} catch {
    FileHandle.standardError.write(Data("오류: \(error)\n".utf8))
    exit(1)
}
