@testable import AnicueDomain
import Foundation
import Testing

@Suite("곡·큐 모델")
struct ModelTests {
    func track(path: String, imported: String? = "2025-04-01") -> Track {
        Track(id: "1", uuid: "u", title: "t", artist: nil, album: nil, albumArtist: nil, genre: nil, composer: nil,
              releaseYear: nil, trackNumber: nil, key: nil, bpm: nil, lengthSeconds: 1, folderPath: path, comment: "",
              importedOn: imported, analysisDataPath: nil, imagePath: nil, isDeleted: false)
    }

    @Test func 확장자와_스트리밍() {
        #expect(track(path: "/Music/곡.FLAC").fileExtension == "flac")
        #expect(track(path: "apple-music:12345").isStreaming && track(path: "apple-music:12345").fileExtension == "stream")
        #expect(track(path: "/a.mp3").importYear == "2025" && track(path: "/a.mp3", imported: nil).importYear == nil)
    }

    @Test func 핫큐_칸과_자동_큐_루프() {
        let slots = [1, 2, 3, 4, 5, 6, 7, 8, 9].map { Cue(id: "", contentID: "", kind: $0, inMsec: 0, name: "", colorTableIndex: nil).hotCueSlot }
        #expect(slots == ["A", "B", "C", nil, "D", "E", "F", "G", "H"])
        #expect(Cue(id: "", contentID: "", kind: 0, inMsec: 0, name: " 1.1Bars ", colorTableIndex: nil).isAutoGenerated)
        #expect(Cue(id: "", contentID: "", kind: 1, inMsec: 1000, name: "", colorTableIndex: nil, outMsec: 5000).isLoop)
        #expect(!Cue(id: "", contentID: "", kind: 1, inMsec: 1000, name: "", colorTableIndex: nil, outMsec: -1).isLoop)
    }

    @Test func 오류_문구는_한국어로_무엇이_문제인지() {
        let errors: [AnicueError] = [.keyDerivationFailed, .databaseOpenFailed(path: "/x", message: "m"), .queryFailed(sql: "s", message: "m"),
                                     .rekordboxRunning, .writeAheadLogPresent(path: "/w"), .sourceChangedDuringCopy(path: "/s"),
                                     .snapshotNotFound, .invalidAnalysisFile("/a"), .invalidCueJSON, .writeRefused("이유"),
                                     .writeVerificationFailed("검증")]
        for error in errors { #expect(!error.description.isEmpty) }
        #expect(AnicueError.writeRefused("이유").description.contains("이유"))
    }
}

@Suite("박 위치·변속")
struct BeatGridPositionTests {
    /// 120 BPM 16박(1.0초부터, 첫 박 번호 3) → 다운비트 2.0, 4.0, 6.0, 8.0
    let grid = BeatGrid(beats: (0..<16).map { BeatGrid.Beat(number: ($0 + 2) % 4 + 1, bpm: 120, time: 1.0 + Double($0) * 0.5) })

    @Test func 마디와_마디점박() {
        #expect(grid.downbeats == [2.0, 4.0, 6.0, 8.0])
        #expect(grid.bar(at: 1.9) == 0 && grid.bar(at: 2.0) == 1 && grid.bar(at: 5.9) == 2)
        #expect(grid.positionText(at: 0.9) == nil)
        #expect(grid.positionText(at: 1.0) == "0.2" && grid.positionText(at: 2.0) == "1.0" && grid.positionText(at: 2.6) == "1.1")
    }

    @Test func 스냅과_박_이동() {
        #expect(grid.snap(2.2) == 2.0 && grid.snap(2.3) == 2.5)
        #expect(grid.nudge(2.0, beats: 2) == 3.0 && grid.nudge(2.0, beats: -10) == 1.0 && grid.nudge(2.0, beats: 100) == 8.5)
    }

    @Test func 변속은_8박_넘게_이어진_템포만() {
        func beats(_ bpm: Double, _ count: Int, from: Double) -> [BeatGrid.Beat] {
            (0..<count).map { BeatGrid.Beat(number: $0 % 4 + 1, bpm: bpm, time: from + Double($0) * 60 / bpm) }
        }
        #expect(grid.tempoChanges.isEmpty)
        let changing = BeatGrid(beats: beats(128, 32, from: 0) + beats(130, 4, from: 15) + beats(150, 32, from: 17))
        #expect(changing.tempoChanges == [128, 150], "4박짜리 130은 흔들림으로 본다")
        let wobble = BeatGrid(beats: beats(128, 32, from: 0) + beats(129, 32, from: 15))
        #expect(wobble.tempoChanges.isEmpty, "2 BPM 안의 흔들림은 같은 템포")
    }
}

@Suite("가져오기 검증·태그 초안")
struct ImportAndTagTests {
    let sent = [GridSegment(start: 0.25, bpm: 150, firstBeatNumber: 1)]

    func rekordboxGrid(start: Double, bpm: Double) -> BeatGrid {
        BeatGrid(beats: (0..<500).map { BeatGrid.Beat(number: $0 % 4 + 1, bpm: bpm, time: start + Double($0) * 60 / bpm) })
    }

    @Test func 보낸_그리드와_비교() {
        typealias Check = StagedTrack.ImportCheck
        #expect(Check.compare(sent: sent, imported: rekordboxGrid(start: 0.25, bpm: 150), duration: 180, checkedOn: "d").result == .matched)
        #expect(Check.compare(sent: sent, imported: rekordboxGrid(start: 0.26, bpm: 150), duration: 180, checkedOn: "d").result == .shifted)
        #expect(Check.compare(sent: sent, imported: rekordboxGrid(start: 0.25, bpm: 151), duration: 180, checkedOn: "d").result == .reanalyzed)
        #expect(Check.compare(sent: sent, imported: nil, duration: 180, checkedOn: "d").result == .pending)
        #expect(Check.compare(sent: [], imported: nil, duration: 180, checkedOn: "d").result == .noGrid)
    }

    @Test func 태그_초안의_바뀐_칸과_문제() {
        let track = Track(id: "1", uuid: "u", title: "원제", artist: "가수", album: nil, albumArtist: nil, genre: nil, composer: nil,
                          releaseYear: 2024, trackNumber: 3, key: nil, bpm: nil, lengthSeconds: 1, folderPath: "/a.mp3",
                          comment: "", importedOn: nil, analysisDataPath: nil, imagePath: nil, isDeleted: false)
        var draft = TagDraft(track: track)
        #expect(!draft.hasChanges && draft.issues.isEmpty)
        draft.fields.comment = "TVA 작품 OP 1"
        draft.fields.year = "2024년"
        draft.fields.title = " "
        #expect(draft.changedKeys == [.title, .year, .comment])
        #expect(draft.issues == ["연도는 숫자여야 합니다", "제목이 비어 있습니다"])
    }
}
