import DJCDomain
import Foundation

/// 읽기 API의 JSON 계약. 선택 값이 없으면 해당 키를 생략한다.
public enum ReadJSON {
    private struct Envelope<Value: Encodable>: Encodable {
        let schemaVersion = 1
        let command: String
        let data: Value
    }

    private struct ErrorEnvelope: Encodable {
        let schemaVersion = 1
        let command: String
        let error: ReadFailure
    }

    public static func encode<T: Encodable>(command: String, data: T) throws -> Data {
        try encoder().encode(Envelope(command: command, data: data))
    }

    public static func error(command: String, error: any Error) throws -> Data {
        let failure = error as? ReadFailure ?? ReadFailure("read_failed", String(ui: "읽지 못했습니다: \(String(describing: error)). 사본과 접근 권한을 확인하세요"))
        return try encoder().encode(ErrorEnvelope(command: command, error: failure))
    }

    private static func encoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return encoder
    }
}

public struct ReadFailure: Error, Codable, CustomStringConvertible {
    public let code: String
    public let message: String
    public var description: String { message }
    public init(_ code: String, _ message: String) { self.code = code; self.message = message }
}

public extension LibraryRead {
    struct TrackRecord: Codable, Sendable {
        public let id: String
        public let uuid: String
        public let title: String
        public let artist: String?
        public let album: String?
        public let albumArtist: String?
        public let genre: String?
        public let composer: String?
        public let releaseYear: Int?
        public let trackNumber: Int?
        public let key: String?
        public let bpm: Double?
        public let lengthSeconds: Int
        public let path: String
        public let comment: String
        public let importedOn: String?
        public let isStreaming: Bool

        init(_ track: Track) {
            id = track.id; uuid = track.uuid; title = track.title; artist = track.artist
            album = track.album; albumArtist = track.albumArtist; genre = track.genre; composer = track.composer
            releaseYear = track.releaseYear; trackNumber = track.trackNumber; key = track.key; bpm = track.bpm
            lengthSeconds = track.lengthSeconds; path = track.folderPath; comment = track.comment
            importedOn = track.importedOn; isStreaming = track.isStreaming
        }
    }

    struct TrackList: Codable { public let tracks: [TrackRecord] }
    struct PathList: Codable { public let paths: [String] }

    struct DuplicateMember: Codable, Sendable, Identifiable {
        public let track: TrackRecord
        public let cueCount: Int
        public let manualCueCount: Int
        public let playlistCount: Int
        public let playCount: Int
        public let format: String
        public let bitrateKbps: Int?
        /// rekordbox `ImagePath`(`/PIONEER/Artwork/…/artwork.jpg`). 그림이 없으면 nil
        public let imagePath: String?
        public var id: String { track.id }
    }

    struct DuplicateGroup: Codable, Sendable, Identifiable {
        public let id: String
        public let tracks: [DuplicateMember]
    }

    struct DuplicateList: Codable, Sendable {
        public let lengthToleranceSeconds: Int
        public let groups: [DuplicateGroup]
    }

    struct CueRecord: Codable {
        public let id: String
        public let kind: Int
        public let hotCueSlot: String?
        public let inMsec: Int
        public let outMsec: Int
        public let name: String
        public let isLoop: Bool
        public let activeLoop: Bool
        public let loopBeats: Double?
        public let isAutoGenerated: Bool
        public let color: Int?
        public let colorTableIndex: Int?

        init(_ cue: Cue) {
            id = cue.id; kind = cue.kind; hotCueSlot = cue.hotCueSlot.map(String.init)
            inMsec = cue.inMsec; outMsec = cue.outMsec; name = cue.name; isLoop = cue.isLoop
            activeLoop = cue.activeLoop > 0; loopBeats = EditableCue.Loop.beats(beatLoopSize: cue.beatLoopSize)
            isAutoGenerated = cue.isAutoGenerated; color = cue.color; colorTableIndex = cue.colorTableIndex
        }
    }

    struct GridRecord: Codable {
        public let status: String
        public let beatCount: Int
        public let segments: [GridSegment]
        public let tempoChanges: [Double]
    }

    struct GainRecord: Codable {
        public let linear: Double
        public let decibels: Double
        public let peak: Double?
    }

    struct DraftState: Codable {
        public let cue: Bool
        public let grid: Bool
        public let gain: Bool
        public let tag: Bool
        public var kinds: [String] {
            [("cue", cue), ("grid", grid), ("gain", gain), ("tag", tag)].compactMap { $0.1 ? $0.0 : nil }
        }
    }

    struct PlaylistRecord: Codable {
        public let id: String
        public let name: String
        public let parentID: String
        public let sequence: Int
        public let isFolder: Bool
        public let trackCount: Int
        public let children: [PlaylistRecord]?
    }

    struct PlaylistList: Codable { public let playlists: [PlaylistRecord] }
    struct PlaylistContents: Codable {
        public let playlist: PlaylistRecord
        public let tracks: [TrackRecord]
    }

    struct HistoryRecord: Codable {
        public let id: String
        public let name: String
        public let dateCreated: String?
        public let trackCount: Int
    }

    struct HistoryEntry: Codable {
        public let id: String
        public let trackNumber: Int
        public let track: TrackRecord
    }

    struct HistoryList: Codable { public let histories: [HistoryRecord] }
    struct HistoryContents: Codable {
        public let history: HistoryRecord
        public let entries: [HistoryEntry]
    }

    struct TrackInfo: Codable {
        public let track: TrackRecord
        public let cues: [CueRecord]
        public let grid: GridRecord
        public let gain: GainRecord?
        public let playlists: [PlaylistRecord]
        public let drafts: DraftState
    }

    struct DraftRecord: Codable {
        public let trackUUID: String
        public let contentID: String?
        public let title: String?
        public let kinds: [String]
    }
    struct DraftList: Codable { public let drafts: [DraftRecord] }

    struct Report: Codable {
        public let totalRows: Int
        public let deletedRows: Int
        public let liveTracks: Int
        public let streamingTracks: Int
        public let extensions: [String: Int]
        public let commentClasses: [String: Int]?
        public let prefixes: [String: Int]?
        public let usages: [String: Int]?
        public let emptyByImportYear: [String: Int]
        public let tracksWithCues: Int
        public let tracksWithManualCues: Int
        public let tracksWithOnlyAutoCues: Int
        public let tracksWithoutCues: Int
        public let hotCueSlots: [String: Int]
        public let playedTracks: Int
        public let emptyCommentPlayed: Int
        public let missingFiles: Int?
    }

    struct ParsedComment: Codable {
        public struct Parsed: Codable {
            public struct Usage: Codable { public let kind: String; public let numbers: [Int] }
            public let prefix: String
            public let workRef: String
            public let workName: String
            public let season: Int?
            public let seasonStyle: String?
            public let abbreviations: [String]
            public let usages: [Usage]
            public let episodes: [Int]
            public let isCharacterSong: Bool
            public let isTVSize: Bool
            public let variants: [String]
            public let isFormerAffiliation: Bool
            public let airingYear: Int?
            public let airingQuarter: Int?
            public let movieYear: Int?
            public let boomboxVolumes: [Int]
        }
        public let classification: String
        public let parsed: Parsed?
    }

    struct Compatibility: Codable {
        public let appVersion: String?
        public let verifiedAppVersions: [String]
        public let databaseVersion: String
        public let localUpdateCount: Int?
        public let cloudUpdateCount: Int?
    }
}
