@testable import DJCDomain
import Foundation
import Testing

@Suite("큐 초안")
struct CueDraftTests {
    let rekordboxCues = [
        Cue(id: "1", contentID: "c", kind: 0, inMsec: 6672, name: "", colorTableIndex: nil),
        Cue(id: "2", contentID: "c", kind: 1, inMsec: 86150, name: "", colorTableIndex: nil),
        Cue(id: "3", contentID: "c", kind: 0, inMsec: 1000, name: "CUE(Auto)", colorTableIndex: nil),
        Cue(id: "4", contentID: "c", kind: 6, inMsec: 6672, name: "", colorTableIndex: nil),
    ]

    /// #145: rekordbox 화면에서 메모리 큐로 보이는 자동 큐(CUE(Auto)·1.1Bars)는 초안에도 이름 그대로 들어간다.
    @Test func rekordbox_자동_큐도_메모리_큐로_불러온다() throws {
        let draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        #expect(draft.cues.map(\.kind) == [.memory, .memory, .hot(4), .hot(0)])
        let auto = try #require(draft.cues.first { $0.sourceID == "3" })
        #expect(auto.name == "CUE(Auto)" && auto.isAutoGenerated)
        #expect(!draft.hasChanges && draft.memoryCount == 2)
    }

    /// 자동 큐를 고치면(옮기기·루프·종류, 지우기 제외) 자동 이름을 비워 일반 큐가 된다. 이름을 바꾸면 그 이름을 둔다.
    @Test func 고친_자동_큐는_이름을_비워_일반_큐가_된다() throws {
        let draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        let auto = try #require(draft.cues.first { $0.sourceID == "3" })
        var moved = draft
        moved.move(auto.id, to: 2)
        #expect(moved.cue(auto.id)?.name == "" && moved.cue(auto.id)?.isAutoGenerated == false)
        var looped = draft
        looped.setLoop(auto.id, end: 3, beats: 4)
        #expect(looped.cue(auto.id)?.name == "")
        var hot = draft, kind = auto
        kind.kind = .hot(2)
        hot.place(kind)
        #expect(hot.cue(auto.id)?.name == "")
        var renamed = draft, name = auto
        name.name = "Drop"
        renamed.place(name)
        #expect(renamed.cue(auto.id)?.name == "Drop")
        var same = draft
        same.place(auto)
        #expect(same == draft, "같은 값으로 다시 놓으면 그대로 자동 큐")
    }

    /// #145 이전 초안은 자동 큐를 빼고 만들었다. base에 없는 자동 큐를 base·cues 양쪽에 채워 변경으로 치지 않는다.
    @Test func 옛_초안에는_자동_큐를_채우고_지운_자동_큐는_되살리지_않는다() throws {
        var old = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        old.base.removeAll(where: \.isAutoGenerated)
        old.cues.removeAll(where: \.isAutoGenerated)
        old.place(EditableCue(kind: .memory, time: 50))
        let upgraded = old.includingAutoCues(from: rekordboxCues)
        #expect(upgraded.base.count == 4 && upgraded.cues.count == 5 && upgraded.changes.count == 1)
        #expect(upgraded.cues.first { $0.sourceID == "3" }?.name == "CUE(Auto)")
        #expect(upgraded.cues.map(\.time) == upgraded.cues.map(\.time).sorted())
        // 지금 초안에서 지운 자동 큐는 base에 있으므로 되살리지 않는다.
        var deleted = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        deleted.remove(try #require(deleted.cues.first { $0.sourceID == "3" }).id)
        #expect(deleted.includingAutoCues(from: rekordboxCues) == deleted)
    }

    @Test func 같은_슬롯에_핫큐를_놓으면_기존_것을_대체한다() {
        var draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        draft.place(EditableCue(kind: .hot(0), time: 120))
        #expect(draft.cues.filter { $0.kind == .hot(0) }.count == 1)
        #expect(draft.cues.first { $0.kind == .hot(0) }?.time == 120)
        let changes = draft.changes
        #expect(changes.contains { if case .removed = $0 { true } else { false } })
        #expect(changes.contains { if case .added = $0 { true } else { false } })
    }

    @Test func 이동과_이름_변경은_수정으로_잡힌다() throws {
        var draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        var cue = try #require(draft.cues.first { $0.sourceID == "1" })
        cue.time = 7.0
        cue.name = "1사비"
        draft.place(cue)
        #expect(draft.changes.count == 1)
        guard case let .modified(from, to) = draft.changes[0] else { Issue.record("수정이 아님"); return }
        #expect(from.time == 6.672 && to.time == 7.0 && to.name == "1사비")
    }

    @Test func 되돌리면_변경이_없다() {
        var draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        draft.remove(draft.cues[0].id)
        #expect(draft.hasChanges)
        draft.revert()
        #expect(!draft.hasChanges)
    }

    @Test func 곡_길이를_벗어난_큐는_문제로_보고한다() {
        var draft = CueDraft(trackUUID: "t", rekordboxCues: rekordboxCues)
        draft.place(EditableCue(kind: .memory, time: 500))
        #expect(!draft.issues(duration: 269).isEmpty)
    }
}
